// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_s (
        ap_clk,
        ap_rst,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [5:0] data_0_val;
input  [5:0] data_1_val;
input  [5:0] data_2_val;
input  [5:0] data_3_val;
input  [5:0] data_4_val;
input  [5:0] data_5_val;
input  [5:0] data_6_val;
input  [5:0] data_7_val;
input  [5:0] data_8_val;
input  [5:0] data_9_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;
reg[15:0] ap_return_6;
reg[15:0] ap_return_7;
reg[15:0] ap_return_8;
reg[15:0] ap_return_9;

reg   [5:0] data_9_val_read_reg_9741;
wire    ap_block_pp0_stage0_11001;
reg   [5:0] data_8_val_read_reg_9751;
reg   [5:0] data_7_val_read_reg_9762;
reg   [5:0] data_6_val_read_reg_9772;
reg   [5:0] data_5_val_read_reg_9784;
reg   [5:0] data_4_val_read_reg_9796;
reg   [5:0] data_3_val_read_reg_9806;
reg   [5:0] data_2_val_read_reg_9817;
reg   [5:0] data_1_val_read_reg_9828;
reg   [5:0] data_0_val_read_reg_9839;
wire   [10:0] zext_ln73_44_fu_6695_p1;
reg   [10:0] zext_ln73_44_reg_9850;
reg   [4:0] lshr_ln42_16_reg_9855;
wire   [10:0] sub_ln73_26_fu_6709_p2;
reg   [10:0] sub_ln73_26_reg_9860;
wire  signed [10:0] sub_ln73_40_fu_6727_p2;
reg  signed [10:0] sub_ln73_40_reg_9865;
reg   [9:0] trunc_ln42_26_reg_9870;
reg   [4:0] lshr_ln42_27_reg_9875;
reg   [4:0] lshr_ln42_29_reg_9880;
wire   [9:0] sub_ln73_67_fu_6779_p2;
reg   [9:0] sub_ln73_67_reg_9885;
reg   [8:0] trunc_ln42_53_reg_9890;
wire   [5:0] mul_ln73_14_fu_204_p0;
wire   [11:0] zext_ln73_16_fu_8159_p1;
wire  signed [5:0] mul_ln73_14_fu_204_p1;
wire    ap_block_pp0_stage0;
wire   [5:0] mul_ln73_7_fu_211_p0;
wire   [10:0] zext_ln73_66_fu_7404_p1;
wire  signed [4:0] mul_ln73_7_fu_211_p1;
wire   [5:0] mul_ln73_4_fu_212_p0;
wire   [4:0] mul_ln73_4_fu_212_p1;
wire   [5:0] mul_ln73_fu_221_p0;
wire   [10:0] zext_ln73_43_fu_6807_p1;
wire   [5:0] mul_ln73_fu_221_p1;
wire   [5:0] mul_ln73_11_fu_225_p0;
wire   [10:0] zext_ln73_93_fu_7944_p1;
wire   [5:0] mul_ln73_11_fu_225_p1;
wire   [5:0] mul_ln73_5_fu_234_p0;
wire   [11:0] zext_ln73_10_fu_7041_p1;
wire  signed [5:0] mul_ln73_5_fu_234_p1;
wire   [5:0] mul_ln73_16_fu_260_p0;
wire   [9:0] zext_ln73_108_fu_8358_p1;
wire   [4:0] mul_ln73_16_fu_260_p1;
wire   [5:0] mul_ln73_8_fu_266_p0;
wire   [5:0] mul_ln73_8_fu_266_p1;
wire   [5:0] mul_ln73_18_fu_269_p0;
wire   [10:0] zext_ln73_107_fu_8354_p1;
wire   [5:0] mul_ln73_18_fu_269_p1;
wire   [5:0] mul_ln73_15_fu_276_p0;
wire   [10:0] zext_ln73_103_fu_8166_p1;
wire   [5:0] mul_ln73_15_fu_276_p1;
wire   [5:0] mul_ln73_10_fu_282_p0;
wire   [10:0] zext_ln73_81_fu_7700_p1;
wire   [5:0] mul_ln73_10_fu_282_p1;
wire   [5:0] mul_ln73_12_fu_287_p0;
wire   [9:0] zext_ln73_92_fu_7940_p1;
wire   [4:0] mul_ln73_12_fu_287_p1;
wire   [5:0] mul_ln73_13_fu_289_p0;
wire   [5:0] mul_ln73_13_fu_289_p1;
wire   [5:0] mul_ln73_9_fu_291_p0;
wire   [5:0] mul_ln73_9_fu_291_p1;
wire   [5:0] mul_ln73_6_fu_292_p0;
wire   [5:0] mul_ln73_6_fu_292_p1;
wire   [5:0] mul_ln73_17_fu_298_p0;
wire   [11:0] zext_ln73_17_fu_8350_p1;
wire  signed [5:0] mul_ln73_17_fu_298_p1;
wire   [9:0] shl_ln73_s_fu_6687_p3;
wire   [9:0] shl_ln73_27_fu_6715_p3;
wire   [10:0] zext_ln73_71_fu_6723_p1;
wire   [8:0] shl_ln73_46_fu_6767_p3;
wire   [9:0] zext_ln73_121_fu_6775_p1;
wire   [9:0] zext_ln73_116_fu_6763_p1;
wire   [9:0] sub_ln73_78_fu_6785_p2;
wire   [10:0] mul_ln73_fu_221_p2;
wire   [9:0] lshr_ln_fu_6811_p4;
wire   [10:0] add_ln73_fu_6825_p2;
wire   [10:0] shl_ln73_15_fu_6840_p3;
wire   [11:0] zext_ln73_45_fu_6847_p1;
wire   [11:0] sub_ln73_24_fu_6851_p2;
wire   [10:0] trunc_ln42_13_fu_6857_p4;
wire   [7:0] shl_ln73_16_fu_6871_p3;
wire   [11:0] zext_ln73_46_fu_6878_p1;
wire   [11:0] sub_ln73_25_fu_6882_p2;
wire   [10:0] lshr_ln42_s_fu_6888_p4;
wire  signed [11:0] sext_ln73_14_fu_6902_p1;
wire   [11:0] zext_ln73_fu_6801_p1;
wire   [11:0] sub_ln73_27_fu_6905_p2;
wire   [10:0] trunc_ln4_fu_6911_p4;
wire   [6:0] shl_ln73_17_fu_6925_p3;
wire   [7:0] zext_ln73_48_fu_6936_p1;
wire   [7:0] sub_ln73_28_fu_6940_p2;
wire   [6:0] trunc_ln42_s_fu_6946_p4;
wire   [11:0] sub_ln73_29_fu_6960_p2;
wire   [10:0] lshr_ln42_17_fu_6966_p4;
wire   [6:0] zext_ln73_42_fu_6804_p1;
wire   [6:0] sub_ln73_fu_6980_p2;
wire   [5:0] trunc_ln42_14_fu_6986_p4;
wire   [8:0] shl_ln73_18_fu_7000_p3;
wire   [9:0] zext_ln73_49_fu_7007_p1;
wire   [9:0] sub_ln73_30_fu_7011_p2;
wire  signed [10:0] sext_ln73_18_fu_7017_p1;
wire   [10:0] zext_ln73_47_fu_6932_p1;
wire   [10:0] sub_ln73_31_fu_7021_p2;
wire   [9:0] trunc_ln42_15_fu_7027_p4;
wire   [9:0] mul_ln73_4_fu_212_p2;
wire   [8:0] lshr_ln42_18_fu_7056_p4;
wire   [11:0] mul_ln73_5_fu_234_p2;
wire   [10:0] trunc_ln42_16_fu_7070_p4;
wire   [10:0] shl_ln73_19_fu_7084_p3;
wire   [11:0] zext_ln73_54_fu_7091_p1;
wire   [11:0] sub_ln73_32_fu_7095_p2;
wire   [10:0] trunc_ln42_17_fu_7101_p4;
wire   [11:0] sub_ln73_33_fu_7115_p2;
wire   [10:0] lshr_ln42_19_fu_7121_p4;
wire   [6:0] shl_ln73_20_fu_7135_p3;
wire   [11:0] zext_ln73_55_fu_7142_p1;
wire   [11:0] sub_ln73_34_fu_7146_p2;
wire  signed [10:0] trunc_ln42_18_fu_7152_p4;
wire   [10:0] mul_ln73_6_fu_292_p2;
wire   [9:0] lshr_ln42_20_fu_7170_p4;
wire   [7:0] shl_ln73_21_fu_7184_p3;
wire   [8:0] zext_ln73_57_fu_7191_p1;
wire   [8:0] zext_ln73_50_fu_7045_p1;
wire   [8:0] sub_ln73_35_fu_7195_p2;
wire   [7:0] trunc_ln42_19_fu_7201_p4;
wire  signed [10:0] sext_ln42_fu_7211_p1;
wire   [10:0] shl_ln73_22_fu_7225_p3;
wire   [11:0] zext_ln73_59_fu_7232_p1;
wire   [11:0] zext_ln73_11_fu_7219_p1;
wire   [11:0] sub_ln73_36_fu_7236_p2;
wire   [10:0] lshr_ln42_21_fu_7242_p4;
wire   [11:0] sub_ln73_37_fu_7256_p2;
wire   [10:0] trunc_ln42_20_fu_7262_p4;
wire   [8:0] shl_ln73_23_fu_7276_p3;
wire   [6:0] shl_ln73_24_fu_7287_p3;
wire   [9:0] zext_ln73_60_fu_7283_p1;
wire   [9:0] zext_ln73_61_fu_7294_p1;
wire   [9:0] add_ln73_2_fu_7298_p2;
wire   [7:0] shl_ln73_25_fu_7314_p3;
wire   [8:0] zext_ln73_63_fu_7325_p1;
wire   [8:0] zext_ln73_58_fu_7222_p1;
wire   [8:0] add_ln73_3_fu_7329_p2;
wire   [7:0] lshr_ln42_22_fu_7335_p4;
wire   [9:0] sub_ln73_38_fu_7349_p2;
wire   [8:0] trunc_ln42_21_fu_7355_p4;
wire  signed [10:0] sext_ln42_1_fu_7365_p1;
wire   [9:0] shl_ln73_26_fu_7373_p3;
wire   [10:0] zext_ln73_62_fu_7321_p1;
wire   [10:0] zext_ln73_65_fu_7380_p1;
wire   [10:0] sub_ln73_39_fu_7384_p2;
wire   [9:0] trunc_ln42_22_fu_7390_p4;
wire   [6:0] shl_ln_fu_7415_p3;
wire   [7:0] shl_ln73_1_fu_7429_p3;
wire   [6:0] zext_ln73_68_fu_7412_p1;
wire   [6:0] sub_ln73_1_fu_7444_p2;
wire   [5:0] trunc_ln42_23_fu_7450_p4;
wire  signed [11:0] sext_ln73_25_fu_7464_p1;
wire   [11:0] zext_ln42_2_fu_7422_p1;
wire   [11:0] sub_ln73_41_fu_7467_p2;
wire   [10:0] trunc_ln42_24_fu_7473_p4;
wire   [10:0] mul_ln73_7_fu_211_p2;
wire   [9:0] trunc_ln42_25_fu_7487_p4;
wire   [10:0] mul_ln73_8_fu_266_p2;
wire   [9:0] lshr_ln42_23_fu_7501_p4;
wire   [10:0] shl_ln73_28_fu_7518_p3;
wire   [11:0] zext_ln73_72_fu_7525_p1;
wire   [11:0] zext_ln42_3_fu_7436_p1;
wire   [11:0] sub_ln73_42_fu_7529_p2;
wire   [10:0] lshr_ln42_24_fu_7535_p4;
wire   [6:0] tmp_1_fu_7556_p3;
wire   [9:0] shl_ln73_29_fu_7571_p3;
wire   [10:0] zext_ln73_76_fu_7578_p1;
wire   [10:0] sub_ln73_43_fu_7582_p2;
wire   [9:0] trunc_ln42_27_fu_7588_p4;
wire   [10:0] shl_ln73_30_fu_7602_p3;
wire   [11:0] zext_ln73_77_fu_7609_p1;
wire   [11:0] sub_ln73_44_fu_7613_p2;
wire   [10:0] trunc_ln42_28_fu_7619_p4;
wire   [10:0] zext_ln73_78_fu_7633_p1;
wire   [10:0] add_ln73_4_fu_7637_p2;
wire   [9:0] lshr_ln42_25_fu_7643_p4;
wire   [11:0] zext_ln73_13_fu_7549_p1;
wire   [11:0] sub_ln73_45_fu_7660_p2;
wire   [10:0] lshr_ln42_26_fu_7666_p4;
wire   [10:0] mul_ln73_9_fu_291_p2;
wire   [9:0] lshr_ln42_28_fu_7683_p4;
wire   [8:0] shl_ln73_31_fu_7707_p3;
wire   [6:0] shl_ln73_32_fu_7718_p3;
wire   [9:0] zext_ln73_85_fu_7729_p1;
wire   [9:0] zext_ln73_83_fu_7714_p1;
wire   [9:0] sub_ln73_46_fu_7733_p2;
wire   [8:0] trunc_ln42_29_fu_7739_p4;
wire   [10:0] shl_ln73_33_fu_7753_p3;
wire   [11:0] zext_ln73_86_fu_7760_p1;
wire   [11:0] sub_ln73_47_fu_7764_p2;
wire   [10:0] trunc_ln42_30_fu_7770_p4;
wire   [9:0] sub_ln73_48_fu_7787_p2;
wire  signed [10:0] sext_ln73_32_fu_7793_p1;
wire   [10:0] sub_ln73_49_fu_7797_p2;
wire   [9:0] trunc_ln42_31_fu_7803_p4;
wire   [9:0] shl_ln73_34_fu_7817_p3;
wire   [10:0] zext_ln73_88_fu_7824_p1;
wire   [10:0] zext_ln73_84_fu_7725_p1;
wire   [10:0] add_ln73_5_fu_7828_p2;
wire   [9:0] lshr_ln42_30_fu_7834_p4;
wire   [11:0] zext_ln73_14_fu_7697_p1;
wire   [11:0] sub_ln73_72_fu_7852_p2;
wire   [10:0] trunc_ln42_32_fu_7858_p4;
wire   [10:0] mul_ln73_10_fu_282_p2;
wire   [9:0] lshr_ln42_31_fu_7872_p4;
wire   [7:0] tmp_3_fu_7886_p3;
wire   [8:0] zext_ln73_82_fu_7704_p1;
wire   [8:0] zext_ln73_91_fu_7893_p1;
wire   [8:0] sub_ln73_73_fu_7897_p2;
wire   [7:0] trunc_ln42_33_fu_7903_p4;
wire   [11:0] sub_ln73_50_fu_7917_p2;
wire   [10:0] lshr_ln42_32_fu_7923_p4;
wire   [10:0] shl_ln73_35_fu_7948_p3;
wire   [11:0] zext_ln73_94_fu_7955_p1;
wire   [11:0] sub_ln73_51_fu_7959_p2;
wire  signed [10:0] trunc_ln42_34_fu_7965_p4;
wire   [9:0] shl_ln73_36_fu_7983_p3;
wire   [7:0] shl_ln73_37_fu_7994_p3;
wire   [10:0] zext_ln73_95_fu_7990_p1;
wire   [10:0] zext_ln73_96_fu_8001_p1;
wire   [10:0] add_ln73_6_fu_8005_p2;
wire   [9:0] lshr_ln42_33_fu_8011_p4;
wire   [11:0] zext_ln73_15_fu_7937_p1;
wire   [11:0] sub_ln73_52_fu_8025_p2;
wire   [10:0] lshr_ln42_34_fu_8031_p4;
wire   [10:0] mul_ln73_11_fu_225_p2;
wire   [9:0] lshr_ln42_35_fu_8045_p4;
wire   [9:0] mul_ln73_12_fu_287_p2;
wire   [8:0] lshr_ln42_36_fu_8059_p4;
wire   [6:0] shl_ln73_38_fu_8073_p3;
wire   [10:0] zext_ln73_100_fu_8080_p1;
wire   [10:0] sub_ln73_53_fu_8084_p2;
wire   [9:0] trunc_ln42_35_fu_8090_p4;
wire   [8:0] tmp_4_fu_8104_p3;
wire   [9:0] zext_ln73_101_fu_8111_p1;
wire   [9:0] sub_ln73_74_fu_8115_p2;
wire   [8:0] trunc_ln42_36_fu_8121_p4;
wire   [10:0] sub_ln73_54_fu_8135_p2;
wire   [9:0] trunc_ln42_37_fu_8141_p4;
wire  signed [10:0] sext_ln42_3_fu_8151_p1;
wire   [6:0] shl_ln73_39_fu_8171_p3;
wire   [7:0] zext_ln73_104_fu_8178_p1;
wire   [7:0] sub_ln73_55_fu_8182_p2;
wire   [6:0] trunc_ln42_40_fu_8188_p4;
wire   [10:0] shl_ln73_40_fu_8202_p3;
wire   [11:0] zext_ln73_105_fu_8209_p1;
wire   [11:0] sub_ln73_56_fu_8213_p2;
wire   [10:0] lshr_ln42_37_fu_8219_p4;
wire   [11:0] sub_ln73_57_fu_8233_p2;
wire  signed [10:0] trunc_ln42_38_fu_8239_p4;
wire   [11:0] sub_ln73_75_fu_8257_p2;
wire   [10:0] trunc_ln42_39_fu_8263_p4;
wire   [10:0] mul_ln73_13_fu_289_p2;
wire   [9:0] lshr_ln42_38_fu_8277_p4;
wire   [7:0] tmp_6_fu_8291_p3;
wire   [8:0] zext_ln73_102_fu_8163_p1;
wire   [8:0] zext_ln73_106_fu_8298_p1;
wire   [8:0] sub_ln73_76_fu_8302_p2;
wire   [7:0] trunc_ln42_43_fu_8308_p4;
wire   [11:0] mul_ln73_14_fu_204_p2;
wire   [10:0] trunc_ln42_41_fu_8322_p4;
wire   [10:0] mul_ln73_15_fu_276_p2;
wire   [9:0] lshr_ln42_39_fu_8336_p4;
wire   [9:0] mul_ln73_16_fu_260_p2;
wire   [8:0] lshr_ln42_40_fu_8362_p4;
wire   [8:0] shl_ln73_41_fu_8376_p3;
wire   [6:0] shl_ln73_42_fu_8387_p3;
wire   [9:0] zext_ln73_110_fu_8383_p1;
wire   [9:0] zext_ln73_112_fu_8398_p1;
wire   [9:0] sub_ln73_58_fu_8402_p2;
wire   [8:0] trunc_ln42_44_fu_8408_p4;
wire  signed [10:0] sext_ln42_4_fu_8418_p1;
wire   [10:0] shl_ln73_43_fu_8426_p3;
wire   [11:0] zext_ln73_113_fu_8433_p1;
wire   [11:0] sub_ln73_59_fu_8437_p2;
wire   [10:0] trunc_ln42_42_fu_8443_p4;
wire   [9:0] sub_ln73_60_fu_8457_p2;
wire  signed [10:0] sext_ln73_47_fu_8463_p1;
wire   [10:0] sub_ln73_61_fu_8467_p2;
wire   [9:0] trunc_ln42_46_fu_8473_p4;
wire   [11:0] sub_ln73_62_fu_8487_p2;
wire   [10:0] lshr_ln42_41_fu_8493_p4;
wire   [7:0] shl_ln73_44_fu_8511_p3;
wire   [8:0] zext_ln73_115_fu_8518_p1;
wire   [8:0] sub_ln73_63_fu_8522_p2;
wire  signed [9:0] sext_ln73_49_fu_8528_p1;
wire   [9:0] sub_ln73_64_fu_8532_p2;
wire   [8:0] trunc_ln42_47_fu_8538_p4;
wire   [11:0] mul_ln73_17_fu_298_p2;
wire   [10:0] trunc_ln42_45_fu_8552_p4;
wire   [10:0] mul_ln73_18_fu_269_p2;
wire   [9:0] lshr_ln42_42_fu_8566_p4;
wire   [10:0] zext_ln73_111_fu_8394_p1;
wire   [10:0] sub_ln73_65_fu_8580_p2;
wire   [9:0] trunc_ln42_48_fu_8586_p4;
wire   [10:0] shl_ln73_45_fu_8609_p3;
wire   [11:0] zext_ln73_119_fu_8616_p1;
wire   [11:0] zext_ln73_18_fu_8600_p1;
wire   [11:0] sub_ln73_66_fu_8620_p2;
wire   [10:0] lshr_ln42_43_fu_8626_p4;
wire  signed [10:0] sext_ln73_52_fu_8644_p1;
wire   [10:0] zext_ln73_118_fu_8606_p1;
wire   [10:0] sub_ln73_68_fu_8647_p2;
wire   [9:0] trunc_ln42_50_fu_8653_p4;
wire   [6:0] shl_ln73_47_fu_8667_p3;
wire   [7:0] zext_ln73_122_fu_8674_p1;
wire   [7:0] sub_ln73_69_fu_8678_p2;
wire   [6:0] trunc_ln42_51_fu_8684_p4;
wire   [11:0] sub_ln73_70_fu_8698_p2;
wire   [10:0] trunc_ln42_49_fu_8704_p4;
wire   [7:0] shl_ln73_48_fu_8718_p3;
wire   [11:0] zext_ln73_123_fu_8725_p1;
wire   [11:0] sub_ln73_71_fu_8729_p2;
wire   [10:0] lshr_ln42_44_fu_8735_p4;
wire   [8:0] zext_ln73_117_fu_8603_p1;
wire   [8:0] zext_ln73_124_fu_8749_p1;
wire   [8:0] sub_ln73_77_fu_8753_p2;
wire   [7:0] trunc_ln42_52_fu_8759_p4;
wire   [5:0] zext_ln58_cast_fu_8776_p3;
wire   [11:0] zext_ln42_12_fu_6976_p1;
wire   [11:0] zext_ln42_27_fu_7369_p1;
wire   [11:0] add_ln58_fu_8787_p2;
wire   [10:0] zext_ln42_16_fu_7511_p1;
wire   [10:0] zext_ln42_24_fu_8576_p1;
wire   [10:0] add_ln58_96_fu_8797_p2;
wire   [10:0] zext_ln73_80_fu_7680_p1;
wire   [10:0] add_ln58_97_fu_8803_p2;
wire   [12:0] zext_ln58_24_fu_8809_p1;
wire   [12:0] zext_ln58_23_fu_8793_p1;
wire   [12:0] add_ln58_98_fu_8813_p2;
wire  signed [11:0] sext_ln73_20_fu_7111_p1;
wire  signed [11:0] sext_ln73_35_fu_7913_p1;
wire   [11:0] add_ln58_99_fu_8823_p2;
wire  signed [11:0] sext_ln73_45_fu_8332_p1;
wire   [11:0] add_ln58_100_fu_8833_p2;
wire  signed [12:0] sext_ln58_69_fu_8839_p1;
wire  signed [12:0] sext_ln73_36_fu_7975_p1;
wire   [12:0] add_ln58_101_fu_8843_p2;
wire  signed [12:0] sext_ln58_68_fu_8829_p1;
wire   [12:0] add_ln58_102_fu_8849_p2;
wire  signed [14:0] sext_ln58_70_fu_8855_p1;
wire   [14:0] zext_ln58_25_fu_8819_p1;
wire   [14:0] add_ln58_103_fu_8859_p2;
wire   [10:0] zext_ln42_fu_6821_p1;
wire   [10:0] zext_ln73_53_fu_7066_p1;
wire   [10:0] add_ln58_104_fu_8869_p2;
wire   [7:0] zext_ln73_67_fu_7409_p1;
wire   [7:0] zext_ln73_74_fu_7563_p1;
wire   [7:0] add_ln58_105_fu_8879_p2;
wire   [11:0] zext_ln58_27_fu_8885_p1;
wire   [11:0] zext_ln42_15_fu_7252_p1;
wire   [11:0] add_ln58_106_fu_8889_p2;
wire   [11:0] zext_ln58_26_fu_8875_p1;
wire   [11:0] add_ln58_107_fu_8895_p2;
wire   [12:0] zext_ln73_120_fu_8640_p1;
wire  signed [12:0] sext_ln73_31_fu_7749_p1;
wire   [12:0] add_ln58_108_fu_8905_p2;
wire   [12:0] zext_ln73_109_fu_8372_p1;
wire  signed [7:0] sext_ln73_40_fu_8198_p1;
wire   [7:0] add_ln58_110_fu_8917_p2;
wire  signed [11:0] sext_ln58_72_fu_8923_p1;
wire  signed [11:0] sext_ln73_37_fu_7979_p1;
wire   [11:0] add_ln58_111_fu_8927_p2;
wire  signed [12:0] sext_ln58_73_fu_8933_p1;
wire   [12:0] add_ln58_109_fu_8911_p2;
wire   [12:0] add_ln58_112_fu_8937_p2;
wire  signed [13:0] sext_ln58_74_fu_8943_p1;
wire   [13:0] zext_ln58_28_fu_8901_p1;
wire   [13:0] add_ln58_113_fu_8947_p2;
wire   [9:0] trunc_ln_fu_6830_p4;
wire   [9:0] zext_ln73_70_fu_7440_p1;
wire   [9:0] add_ln58_114_fu_8957_p2;
wire   [11:0] zext_ln42_21_fu_8229_p1;
wire   [11:0] zext_ln42_29_fu_8422_p1;
wire   [11:0] add_ln58_115_fu_8967_p2;
wire   [12:0] zext_ln58_30_fu_8973_p1;
wire   [12:0] zext_ln73_97_fu_8021_p1;
wire   [12:0] add_ln58_116_fu_8977_p2;
wire   [12:0] zext_ln58_29_fu_8963_p1;
wire   [12:0] add_ln58_117_fu_8983_p2;
wire  signed [11:0] sext_ln73_19_fu_7080_p1;
wire  signed [11:0] sext_ln73_23_fu_7272_p1;
wire   [11:0] add_ln58_118_fu_8993_p2;
wire  signed [12:0] sext_ln58_76_fu_8999_p1;
wire   [12:0] add_ln58_119_fu_9003_p2;
wire  signed [11:0] sext_ln42_2_fu_7780_p1;
wire   [11:0] add_ln58_120_fu_9013_p2;
wire  signed [11:0] sext_ln73_29_fu_7598_p1;
wire   [11:0] add_ln58_121_fu_9019_p2;
wire  signed [13:0] sext_ln58_78_fu_9025_p1;
wire  signed [13:0] sext_ln58_77_fu_9009_p1;
wire   [13:0] add_ln58_122_fu_9029_p2;
wire  signed [14:0] sext_ln58_79_fu_9035_p1;
wire   [14:0] zext_ln58_31_fu_8989_p1;
wire   [14:0] add_ln58_123_fu_9039_p2;
wire   [8:0] trunc_ln73_1_fu_7304_p4;
wire   [8:0] zext_ln73_69_fu_7426_p1;
wire   [8:0] add_ln58_124_fu_9049_p2;
wire   [11:0] zext_ln42_20_fu_8041_p1;
wire   [11:0] zext_ln42_25_fu_8636_p1;
wire   [11:0] add_ln58_125_fu_9059_p2;
wire   [12:0] zext_ln58_33_fu_9065_p1;
wire   [12:0] zext_ln73_87_fu_7784_p1;
wire   [12:0] add_ln58_126_fu_9069_p2;
wire   [12:0] zext_ln58_32_fu_9055_p1;
wire   [12:0] add_ln58_127_fu_9075_p2;
wire  signed [11:0] sext_ln73_fu_6867_p1;
wire   [11:0] add_ln58_128_fu_9085_p2;
wire  signed [11:0] sext_ln73_46_fu_8453_p1;
wire   [11:0] add_ln58_129_fu_9095_p2;
wire  signed [12:0] sext_ln58_82_fu_9101_p1;
wire  signed [12:0] sext_ln73_42_fu_8253_p1;
wire   [12:0] add_ln58_130_fu_9105_p2;
wire  signed [13:0] sext_ln58_83_fu_9111_p1;
wire  signed [13:0] sext_ln58_81_fu_9091_p1;
wire   [13:0] add_ln58_131_fu_9115_p2;
wire  signed [14:0] sext_ln58_84_fu_9121_p1;
wire   [14:0] zext_ln58_34_fu_9081_p1;
wire   [14:0] add_ln58_132_fu_9125_p2;
wire   [11:0] zext_ln42_11_fu_6898_p1;
wire   [11:0] zext_ln42_13_fu_7131_p1;
wire   [11:0] add_ln58_133_fu_9135_p2;
wire   [10:0] zext_ln73_98_fu_8055_p1;
wire  signed [10:0] sext_ln73_24_fu_7460_p1;
wire   [10:0] add_ln58_134_fu_9145_p2;
wire   [10:0] zext_ln73_64_fu_7345_p1;
wire   [10:0] add_ln58_135_fu_9151_p2;
wire  signed [13:0] sext_ln58_86_fu_9157_p1;
wire   [13:0] zext_ln58_35_fu_9141_p1;
wire   [13:0] add_ln58_136_fu_9161_p2;
wire  signed [11:0] sext_ln73_33_fu_7813_p1;
wire  signed [11:0] sext_ln73_43_fu_8273_p1;
wire   [11:0] add_ln58_137_fu_9171_p2;
wire  signed [12:0] sext_ln58_88_fu_9177_p1;
wire  signed [12:0] sext_ln73_30_fu_7629_p1;
wire  signed [10:0] sext_ln73_53_fu_8663_p1;
wire   [10:0] add_ln58_139_fu_9187_p2;
wire  signed [11:0] sext_ln58_89_fu_9193_p1;
wire  signed [11:0] sext_ln73_48_fu_8483_p1;
wire   [11:0] add_ln58_140_fu_9197_p2;
wire  signed [12:0] sext_ln58_90_fu_9203_p1;
wire   [12:0] add_ln58_138_fu_9181_p2;
wire   [12:0] add_ln58_141_fu_9207_p2;
wire  signed [14:0] sext_ln58_91_fu_9213_p1;
wire  signed [14:0] sext_ln58_87_fu_9167_p1;
wire   [14:0] add_ln58_142_fu_9217_p2;
wire   [11:0] zext_ln42_4_fu_7653_p1;
wire   [11:0] add_ln58_143_fu_9227_p2;
wire   [10:0] zext_ln73_99_fu_8069_p1;
wire   [10:0] zext_ln42_22_fu_8287_p1;
wire   [10:0] add_ln58_144_fu_9237_p2;
wire   [10:0] zext_ln42_19_fu_7844_p1;
wire   [10:0] add_ln58_145_fu_9243_p2;
wire   [12:0] zext_ln58_37_fu_9249_p1;
wire   [12:0] zext_ln58_36_fu_9233_p1;
wire   [12:0] add_ln58_146_fu_9253_p2;
wire   [11:0] zext_ln42_23_fu_8503_p1;
wire   [11:0] zext_ln58_fu_8783_p1;
wire   [11:0] add_ln58_147_fu_9263_p2;
wire  signed [11:0] sext_ln73_26_fu_7483_p1;
wire  signed [11:0] sext_ln73_54_fu_8694_p1;
wire   [11:0] add_ln58_148_fu_9273_p2;
wire  signed [12:0] sext_ln58_93_fu_9279_p1;
wire  signed [12:0] sext_ln73_22_fu_7166_p1;
wire   [12:0] add_ln58_149_fu_9283_p2;
wire  signed [13:0] sext_ln58_94_fu_9289_p1;
wire   [13:0] zext_ln58_39_fu_9269_p1;
wire   [13:0] add_ln58_150_fu_9293_p2;
wire  signed [14:0] sext_ln58_95_fu_9299_p1;
wire   [14:0] zext_ln58_38_fu_9259_p1;
wire   [14:0] add_ln58_151_fu_9303_p2;
wire   [11:0] add_ln58_152_fu_9313_p2;
wire  signed [11:0] sext_ln73_15_fu_6921_p1;
wire   [11:0] add_ln58_153_fu_9323_p2;
wire  signed [12:0] sext_ln58_97_fu_9329_p1;
wire   [12:0] zext_ln73_79_fu_7657_p1;
wire   [12:0] add_ln58_154_fu_9333_p2;
wire  signed [13:0] sext_ln58_98_fu_9339_p1;
wire   [13:0] zext_ln58_40_fu_9319_p1;
wire   [13:0] add_ln58_155_fu_9343_p2;
wire  signed [10:0] sext_ln73_39_fu_8100_p1;
wire  signed [10:0] sext_ln73_44_fu_8318_p1;
wire   [10:0] add_ln58_156_fu_9353_p2;
wire  signed [11:0] sext_ln58_100_fu_9359_p1;
wire  signed [11:0] sext_ln73_34_fu_7868_p1;
wire   [11:0] add_ln58_157_fu_9363_p2;
wire  signed [11:0] sext_ln73_55_fu_8714_p1;
wire   [11:0] add_ln58_158_fu_9373_p2;
wire  signed [12:0] sext_ln58_102_fu_9379_p1;
wire  signed [12:0] sext_ln73_50_fu_8548_p1;
wire   [12:0] add_ln58_159_fu_9383_p2;
wire  signed [12:0] sext_ln58_101_fu_9369_p1;
wire   [12:0] add_ln58_160_fu_9389_p2;
wire  signed [14:0] sext_ln58_103_fu_9395_p1;
wire  signed [14:0] sext_ln58_99_fu_9349_p1;
wire   [14:0] add_ln58_161_fu_9399_p2;
wire   [11:0] zext_ln73_56_fu_7180_p1;
wire   [11:0] zext_ln42_18_fu_7676_p1;
wire   [11:0] add_ln58_162_fu_9409_p2;
wire   [11:0] zext_ln42_26_fu_8745_p1;
wire   [11:0] add_ln58_163_fu_9419_p2;
wire   [12:0] zext_ln58_42_fu_9425_p1;
wire   [12:0] zext_ln73_90_fu_7882_p1;
wire   [12:0] add_ln58_164_fu_9429_p2;
wire   [12:0] zext_ln58_41_fu_9415_p1;
wire   [12:0] add_ln58_165_fu_9435_p2;
wire  signed [11:0] sext_ln73_27_fu_7497_p1;
wire   [11:0] add_ln58_166_fu_9445_p2;
wire  signed [11:0] sext_ln73_16_fu_6956_p1;
wire   [11:0] add_ln58_167_fu_9451_p2;
wire  signed [11:0] sext_ln73_51_fu_8562_p1;
wire   [11:0] add_ln58_168_fu_9461_p2;
wire  signed [11:0] sext_ln73_38_fu_8131_p1;
wire   [11:0] add_ln58_169_fu_9467_p2;
wire  signed [12:0] sext_ln58_106_fu_9473_p1;
wire  signed [12:0] sext_ln58_105_fu_9457_p1;
wire   [12:0] add_ln58_170_fu_9477_p2;
wire  signed [14:0] sext_ln58_107_fu_9483_p1;
wire   [14:0] zext_ln58_43_fu_9441_p1;
wire   [14:0] add_ln58_171_fu_9487_p2;
wire   [11:0] zext_ln70_fu_7693_p1;
wire   [11:0] add_ln58_172_fu_9497_p2;
wire   [11:0] zext_ln42_28_fu_8155_p1;
wire   [11:0] zext_ln70_3_fu_8346_p1;
wire   [11:0] add_ln58_173_fu_9507_p2;
wire   [11:0] zext_ln73_89_fu_7848_p1;
wire   [11:0] add_ln58_174_fu_9513_p2;
wire   [12:0] zext_ln58_45_fu_9519_p1;
wire   [12:0] zext_ln58_44_fu_9503_p1;
wire   [12:0] add_ln58_175_fu_9523_p2;
wire  signed [11:0] sext_ln73_17_fu_6996_p1;
wire  signed [11:0] sext_ln73_21_fu_7162_p1;
wire   [11:0] add_ln58_176_fu_9533_p2;
wire  signed [12:0] sext_ln58_109_fu_9539_p1;
wire   [12:0] zext_ln73_114_fu_8507_p1;
wire  signed [8:0] sext_ln73_56_fu_8769_p1;
wire   [8:0] add_ln58_178_fu_9549_p2;
wire  signed [10:0] sext_ln58_110_fu_9555_p1;
wire  signed [10:0] sext_ln73_28_fu_7515_p1;
wire   [10:0] add_ln58_179_fu_9559_p2;
wire  signed [12:0] sext_ln58_111_fu_9565_p1;
wire   [12:0] add_ln58_177_fu_9543_p2;
wire   [12:0] add_ln58_180_fu_9569_p2;
wire  signed [14:0] sext_ln58_112_fu_9575_p1;
wire   [14:0] zext_ln58_46_fu_9529_p1;
wire   [14:0] add_ln58_181_fu_9579_p2;
wire   [11:0] zext_ln42_14_fu_7215_p1;
wire   [11:0] zext_ln42_17_fu_7545_p1;
wire   [11:0] add_ln58_182_fu_9589_p2;
wire   [12:0] zext_ln70_2_fu_7933_p1;
wire  signed [12:0] sext_ln70_fu_7037_p1;
wire   [12:0] add_ln58_183_fu_9599_p2;
wire   [12:0] zext_ln73_75_fu_7567_p1;
wire   [12:0] add_ln58_184_fu_9605_p2;
wire  signed [13:0] sext_ln58_114_fu_9611_p1;
wire   [13:0] zext_ln58_47_fu_9595_p1;
wire   [13:0] add_ln58_185_fu_9615_p2;
wire  signed [11:0] sext_ln73_41_fu_8249_p1;
wire   [11:0] add_ln58_186_fu_9625_p2;
wire  signed [11:0] sext_ln70_10_fu_7400_p1;
wire   [11:0] add_ln58_187_fu_9631_p2;
wire  signed [9:0] sext_ln58_fu_8773_p1;
wire   [9:0] add_ln58_188_fu_9641_p2;
wire   [11:0] zext_ln58_48_fu_9647_p1;
wire  signed [11:0] sext_ln70_11_fu_8596_p1;
wire   [11:0] add_ln58_189_fu_9651_p2;
wire  signed [12:0] sext_ln58_117_fu_9657_p1;
wire  signed [12:0] sext_ln58_116_fu_9637_p1;
wire   [12:0] add_ln58_190_fu_9661_p2;
wire  signed [14:0] sext_ln58_118_fu_9667_p1;
wire  signed [14:0] sext_ln58_115_fu_9621_p1;
wire   [14:0] add_ln58_191_fu_9671_p2;
wire  signed [15:0] sext_ln58_75_fu_8953_p1;
wire  signed [15:0] sext_ln58_80_fu_9045_p1;
wire  signed [15:0] sext_ln58_85_fu_9131_p1;
wire  signed [15:0] sext_ln58_92_fu_9223_p1;
wire  signed [15:0] sext_ln58_96_fu_9309_p1;
wire  signed [15:0] sext_ln58_104_fu_9405_p1;
wire  signed [15:0] sext_ln58_108_fu_9493_p1;
wire  signed [15:0] sext_ln58_71_fu_8865_p1;
wire  signed [15:0] sext_ln58_113_fu_9585_p1;
wire  signed [15:0] sext_ln68_fu_9677_p1;
reg    ap_ce_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;
reg   [15:0] ap_return_6_int_reg;
reg   [15:0] ap_return_7_int_reg;
reg   [15:0] ap_return_8_int_reg;
reg   [15:0] ap_return_9_int_reg;
wire   [9:0] mul_ln73_4_fu_212_p00;
wire   [10:0] mul_ln73_6_fu_292_p00;
wire   [10:0] mul_ln73_9_fu_291_p00;

myproject_mul_6ns_6s_12_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mul_6ns_6s_12_1_0_U40(
    .din0(mul_ln73_14_fu_204_p0),
    .din1(mul_ln73_14_fu_204_p1),
    .dout(mul_ln73_14_fu_204_p2)
);

myproject_mul_6ns_5s_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 11 ))
mul_6ns_5s_11_1_0_U41(
    .din0(mul_ln73_7_fu_211_p0),
    .din1(mul_ln73_7_fu_211_p1),
    .dout(mul_ln73_7_fu_211_p2)
);

myproject_mul_6ns_5ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 10 ))
mul_6ns_5ns_10_1_0_U42(
    .din0(mul_ln73_4_fu_212_p0),
    .din1(mul_ln73_4_fu_212_p1),
    .dout(mul_ln73_4_fu_212_p2)
);

myproject_mul_6ns_6ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_0_U43(
    .din0(mul_ln73_fu_221_p0),
    .din1(mul_ln73_fu_221_p1),
    .dout(mul_ln73_fu_221_p2)
);

myproject_mul_6ns_6ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_0_U44(
    .din0(mul_ln73_11_fu_225_p0),
    .din1(mul_ln73_11_fu_225_p1),
    .dout(mul_ln73_11_fu_225_p2)
);

myproject_mul_6ns_6s_12_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mul_6ns_6s_12_1_0_U45(
    .din0(mul_ln73_5_fu_234_p0),
    .din1(mul_ln73_5_fu_234_p1),
    .dout(mul_ln73_5_fu_234_p2)
);

myproject_mul_6ns_5ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 10 ))
mul_6ns_5ns_10_1_0_U46(
    .din0(mul_ln73_16_fu_260_p0),
    .din1(mul_ln73_16_fu_260_p1),
    .dout(mul_ln73_16_fu_260_p2)
);

myproject_mul_6ns_6ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_0_U47(
    .din0(mul_ln73_8_fu_266_p0),
    .din1(mul_ln73_8_fu_266_p1),
    .dout(mul_ln73_8_fu_266_p2)
);

myproject_mul_6ns_6ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_0_U48(
    .din0(mul_ln73_18_fu_269_p0),
    .din1(mul_ln73_18_fu_269_p1),
    .dout(mul_ln73_18_fu_269_p2)
);

myproject_mul_6ns_6ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_0_U49(
    .din0(mul_ln73_15_fu_276_p0),
    .din1(mul_ln73_15_fu_276_p1),
    .dout(mul_ln73_15_fu_276_p2)
);

myproject_mul_6ns_6ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_0_U50(
    .din0(mul_ln73_10_fu_282_p0),
    .din1(mul_ln73_10_fu_282_p1),
    .dout(mul_ln73_10_fu_282_p2)
);

myproject_mul_6ns_5ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 10 ))
mul_6ns_5ns_10_1_0_U51(
    .din0(mul_ln73_12_fu_287_p0),
    .din1(mul_ln73_12_fu_287_p1),
    .dout(mul_ln73_12_fu_287_p2)
);

myproject_mul_6ns_6ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_0_U52(
    .din0(mul_ln73_13_fu_289_p0),
    .din1(mul_ln73_13_fu_289_p1),
    .dout(mul_ln73_13_fu_289_p2)
);

myproject_mul_6ns_6ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_0_U53(
    .din0(mul_ln73_9_fu_291_p0),
    .din1(mul_ln73_9_fu_291_p1),
    .dout(mul_ln73_9_fu_291_p2)
);

myproject_mul_6ns_6ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mul_6ns_6ns_11_1_0_U54(
    .din0(mul_ln73_6_fu_292_p0),
    .din1(mul_ln73_6_fu_292_p1),
    .dout(mul_ln73_6_fu_292_p2)
);

myproject_mul_6ns_6s_12_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mul_6ns_6s_12_1_0_U55(
    .din0(mul_ln73_17_fu_298_p0),
    .din1(mul_ln73_17_fu_298_p1),
    .dout(mul_ln73_17_fu_298_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= sext_ln58_75_fu_8953_p1;
        ap_return_1_int_reg <= sext_ln58_80_fu_9045_p1;
        ap_return_2_int_reg <= sext_ln58_85_fu_9131_p1;
        ap_return_3_int_reg <= sext_ln58_92_fu_9223_p1;
        ap_return_4_int_reg <= sext_ln58_96_fu_9309_p1;
        ap_return_5_int_reg <= sext_ln58_104_fu_9405_p1;
        ap_return_6_int_reg <= sext_ln58_108_fu_9493_p1;
        ap_return_7_int_reg <= sext_ln58_71_fu_8865_p1;
        ap_return_8_int_reg <= sext_ln58_113_fu_9585_p1;
        ap_return_9_int_reg <= sext_ln68_fu_9677_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        data_0_val_read_reg_9839 <= data_0_val;
        data_1_val_read_reg_9828 <= data_1_val;
        data_2_val_read_reg_9817 <= data_2_val;
        data_3_val_read_reg_9806 <= data_3_val;
        data_4_val_read_reg_9796 <= data_4_val;
        data_5_val_read_reg_9784 <= data_5_val;
        data_6_val_read_reg_9772 <= data_6_val;
        data_7_val_read_reg_9762 <= data_7_val;
        data_8_val_read_reg_9751 <= data_8_val;
        data_9_val_read_reg_9741 <= data_9_val;
        lshr_ln42_16_reg_9855 <= {{data_0_val[5:1]}};
        lshr_ln42_27_reg_9875 <= {{data_4_val[5:1]}};
        lshr_ln42_29_reg_9880 <= {{data_5_val[5:1]}};
        sub_ln73_26_reg_9860[10 : 4] <= sub_ln73_26_fu_6709_p2[10 : 4];
        sub_ln73_40_reg_9865[10 : 4] <= sub_ln73_40_fu_6727_p2[10 : 4];
        sub_ln73_67_reg_9885[9 : 3] <= sub_ln73_67_fu_6779_p2[9 : 3];
        trunc_ln42_26_reg_9870 <= {{sub_ln73_40_fu_6727_p2[10:1]}};
        trunc_ln42_53_reg_9890 <= {{sub_ln73_78_fu_6785_p2[9:1]}};
        zext_ln73_44_reg_9850[9 : 4] <= zext_ln73_44_fu_6695_p1[9 : 4];
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln58_75_fu_8953_p1;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = sext_ln58_80_fu_9045_p1;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = sext_ln58_85_fu_9131_p1;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = sext_ln58_92_fu_9223_p1;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = sext_ln58_96_fu_9309_p1;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = sext_ln58_104_fu_9405_p1;
    end else begin
        ap_return_5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_6 = ap_return_6_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_6 = sext_ln58_108_fu_9493_p1;
    end else begin
        ap_return_6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_7 = ap_return_7_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_7 = sext_ln58_71_fu_8865_p1;
    end else begin
        ap_return_7 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_8 = ap_return_8_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_8 = sext_ln58_113_fu_9585_p1;
    end else begin
        ap_return_8 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_9 = ap_return_9_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_9 = sext_ln68_fu_9677_p1;
    end else begin
        ap_return_9 = 'bx;
    end
end

assign add_ln58_100_fu_8833_p2 = ($signed(sext_ln73_45_fu_8332_p1) + $signed(12'd192));

assign add_ln58_101_fu_8843_p2 = ($signed(sext_ln58_69_fu_8839_p1) + $signed(sext_ln73_36_fu_7975_p1));

assign add_ln58_102_fu_8849_p2 = ($signed(add_ln58_101_fu_8843_p2) + $signed(sext_ln58_68_fu_8829_p1));

assign add_ln58_103_fu_8859_p2 = ($signed(sext_ln58_70_fu_8855_p1) + $signed(zext_ln58_25_fu_8819_p1));

assign add_ln58_104_fu_8869_p2 = (zext_ln42_fu_6821_p1 + zext_ln73_53_fu_7066_p1);

assign add_ln58_105_fu_8879_p2 = (zext_ln73_67_fu_7409_p1 + zext_ln73_74_fu_7563_p1);

assign add_ln58_106_fu_8889_p2 = (zext_ln58_27_fu_8885_p1 + zext_ln42_15_fu_7252_p1);

assign add_ln58_107_fu_8895_p2 = (add_ln58_106_fu_8889_p2 + zext_ln58_26_fu_8875_p1);

assign add_ln58_108_fu_8905_p2 = ($signed(zext_ln73_120_fu_8640_p1) + $signed(sext_ln73_31_fu_7749_p1));

assign add_ln58_109_fu_8911_p2 = (add_ln58_108_fu_8905_p2 + zext_ln73_109_fu_8372_p1);

assign add_ln58_110_fu_8917_p2 = ($signed(sext_ln73_40_fu_8198_p1) + $signed(8'd32));

assign add_ln58_111_fu_8927_p2 = ($signed(sext_ln58_72_fu_8923_p1) + $signed(sext_ln73_37_fu_7979_p1));

assign add_ln58_112_fu_8937_p2 = ($signed(sext_ln58_73_fu_8933_p1) + $signed(add_ln58_109_fu_8911_p2));

assign add_ln58_113_fu_8947_p2 = ($signed(sext_ln58_74_fu_8943_p1) + $signed(zext_ln58_28_fu_8901_p1));

assign add_ln58_114_fu_8957_p2 = (trunc_ln_fu_6830_p4 + zext_ln73_70_fu_7440_p1);

assign add_ln58_115_fu_8967_p2 = (zext_ln42_21_fu_8229_p1 + zext_ln42_29_fu_8422_p1);

assign add_ln58_116_fu_8977_p2 = (zext_ln58_30_fu_8973_p1 + zext_ln73_97_fu_8021_p1);

assign add_ln58_117_fu_8983_p2 = (add_ln58_116_fu_8977_p2 + zext_ln58_29_fu_8963_p1);

assign add_ln58_118_fu_8993_p2 = ($signed(sext_ln73_19_fu_7080_p1) + $signed(sext_ln73_23_fu_7272_p1));

assign add_ln58_119_fu_9003_p2 = ($signed(sext_ln58_76_fu_8999_p1) + $signed(zext_ln73_120_fu_8640_p1));

assign add_ln58_120_fu_9013_p2 = ($signed(sext_ln42_2_fu_7780_p1) + $signed(12'd224));

assign add_ln58_121_fu_9019_p2 = ($signed(add_ln58_120_fu_9013_p2) + $signed(sext_ln73_29_fu_7598_p1));

assign add_ln58_122_fu_9029_p2 = ($signed(sext_ln58_78_fu_9025_p1) + $signed(sext_ln58_77_fu_9009_p1));

assign add_ln58_123_fu_9039_p2 = ($signed(sext_ln58_79_fu_9035_p1) + $signed(zext_ln58_31_fu_8989_p1));

assign add_ln58_124_fu_9049_p2 = (trunc_ln73_1_fu_7304_p4 + zext_ln73_69_fu_7426_p1);

assign add_ln58_125_fu_9059_p2 = (zext_ln42_20_fu_8041_p1 + zext_ln42_25_fu_8636_p1);

assign add_ln58_126_fu_9069_p2 = (zext_ln58_33_fu_9065_p1 + zext_ln73_87_fu_7784_p1);

assign add_ln58_127_fu_9075_p2 = (add_ln58_126_fu_9069_p2 + zext_ln58_32_fu_9055_p1);

assign add_ln58_128_fu_9085_p2 = ($signed(sext_ln73_fu_6867_p1) + $signed(sext_ln73_20_fu_7111_p1));

assign add_ln58_129_fu_9095_p2 = ($signed(sext_ln73_46_fu_8453_p1) + $signed(12'd4064));

assign add_ln58_130_fu_9105_p2 = ($signed(sext_ln58_82_fu_9101_p1) + $signed(sext_ln73_42_fu_8253_p1));

assign add_ln58_131_fu_9115_p2 = ($signed(sext_ln58_83_fu_9111_p1) + $signed(sext_ln58_81_fu_9091_p1));

assign add_ln58_132_fu_9125_p2 = ($signed(sext_ln58_84_fu_9121_p1) + $signed(zext_ln58_34_fu_9081_p1));

assign add_ln58_133_fu_9135_p2 = (zext_ln42_11_fu_6898_p1 + zext_ln42_13_fu_7131_p1);

assign add_ln58_134_fu_9145_p2 = ($signed(zext_ln73_98_fu_8055_p1) + $signed(sext_ln73_24_fu_7460_p1));

assign add_ln58_135_fu_9151_p2 = (add_ln58_134_fu_9145_p2 + zext_ln73_64_fu_7345_p1);

assign add_ln58_136_fu_9161_p2 = ($signed(sext_ln58_86_fu_9157_p1) + $signed(zext_ln58_35_fu_9141_p1));

assign add_ln58_137_fu_9171_p2 = ($signed(sext_ln73_33_fu_7813_p1) + $signed(sext_ln73_43_fu_8273_p1));

assign add_ln58_138_fu_9181_p2 = ($signed(sext_ln58_88_fu_9177_p1) + $signed(sext_ln73_30_fu_7629_p1));

assign add_ln58_139_fu_9187_p2 = ($signed(sext_ln73_53_fu_8663_p1) + $signed(11'd224));

assign add_ln58_140_fu_9197_p2 = ($signed(sext_ln58_89_fu_9193_p1) + $signed(sext_ln73_48_fu_8483_p1));

assign add_ln58_141_fu_9207_p2 = ($signed(sext_ln58_90_fu_9203_p1) + $signed(add_ln58_138_fu_9181_p2));

assign add_ln58_142_fu_9217_p2 = ($signed(sext_ln58_91_fu_9213_p1) + $signed(sext_ln58_87_fu_9167_p1));

assign add_ln58_143_fu_9227_p2 = (zext_ln42_15_fu_7252_p1 + zext_ln42_4_fu_7653_p1);

assign add_ln58_144_fu_9237_p2 = (zext_ln73_99_fu_8069_p1 + zext_ln42_22_fu_8287_p1);

assign add_ln58_145_fu_9243_p2 = (add_ln58_144_fu_9237_p2 + zext_ln42_19_fu_7844_p1);

assign add_ln58_146_fu_9253_p2 = (zext_ln58_37_fu_9249_p1 + zext_ln58_36_fu_9233_p1);

assign add_ln58_147_fu_9263_p2 = (zext_ln42_23_fu_8503_p1 + zext_ln58_fu_8783_p1);

assign add_ln58_148_fu_9273_p2 = ($signed(sext_ln73_26_fu_7483_p1) + $signed(sext_ln73_54_fu_8694_p1));

assign add_ln58_149_fu_9283_p2 = ($signed(sext_ln58_93_fu_9279_p1) + $signed(sext_ln73_22_fu_7166_p1));

assign add_ln58_150_fu_9293_p2 = ($signed(sext_ln58_94_fu_9289_p1) + $signed(zext_ln58_39_fu_9269_p1));

assign add_ln58_151_fu_9303_p2 = ($signed(sext_ln58_95_fu_9299_p1) + $signed(zext_ln58_38_fu_9259_p1));

assign add_ln58_152_fu_9313_p2 = (zext_ln42_15_fu_7252_p1 + zext_ln42_2_fu_7422_p1);

assign add_ln58_153_fu_9323_p2 = ($signed(sext_ln73_15_fu_6921_p1) + $signed(sext_ln73_19_fu_7080_p1));

assign add_ln58_154_fu_9333_p2 = ($signed(sext_ln58_97_fu_9329_p1) + $signed(zext_ln73_79_fu_7657_p1));

assign add_ln58_155_fu_9343_p2 = ($signed(sext_ln58_98_fu_9339_p1) + $signed(zext_ln58_40_fu_9319_p1));

assign add_ln58_156_fu_9353_p2 = ($signed(sext_ln73_39_fu_8100_p1) + $signed(sext_ln73_44_fu_8318_p1));

assign add_ln58_157_fu_9363_p2 = ($signed(sext_ln58_100_fu_9359_p1) + $signed(sext_ln73_34_fu_7868_p1));

assign add_ln58_158_fu_9373_p2 = ($signed(sext_ln73_55_fu_8714_p1) + $signed(12'd992));

assign add_ln58_159_fu_9383_p2 = ($signed(sext_ln58_102_fu_9379_p1) + $signed(sext_ln73_50_fu_8548_p1));

assign add_ln58_160_fu_9389_p2 = ($signed(add_ln58_159_fu_9383_p2) + $signed(sext_ln58_101_fu_9369_p1));

assign add_ln58_161_fu_9399_p2 = ($signed(sext_ln58_103_fu_9395_p1) + $signed(sext_ln58_99_fu_9349_p1));

assign add_ln58_162_fu_9409_p2 = (zext_ln73_56_fu_7180_p1 + zext_ln42_18_fu_7676_p1);

assign add_ln58_163_fu_9419_p2 = (zext_ln42_21_fu_8229_p1 + zext_ln42_26_fu_8745_p1);

assign add_ln58_164_fu_9429_p2 = (zext_ln58_42_fu_9425_p1 + zext_ln73_90_fu_7882_p1);

assign add_ln58_165_fu_9435_p2 = (add_ln58_164_fu_9429_p2 + zext_ln58_41_fu_9415_p1);

assign add_ln58_166_fu_9445_p2 = ($signed(sext_ln73_23_fu_7272_p1) + $signed(sext_ln73_27_fu_7497_p1));

assign add_ln58_167_fu_9451_p2 = ($signed(add_ln58_166_fu_9445_p2) + $signed(sext_ln73_16_fu_6956_p1));

assign add_ln58_168_fu_9461_p2 = ($signed(sext_ln73_51_fu_8562_p1) + $signed(12'd576));

assign add_ln58_169_fu_9467_p2 = ($signed(add_ln58_168_fu_9461_p2) + $signed(sext_ln73_38_fu_8131_p1));

assign add_ln58_170_fu_9477_p2 = ($signed(sext_ln58_106_fu_9473_p1) + $signed(sext_ln58_105_fu_9457_p1));

assign add_ln58_171_fu_9487_p2 = ($signed(sext_ln58_107_fu_9483_p1) + $signed(zext_ln58_43_fu_9441_p1));

assign add_ln58_172_fu_9497_p2 = (zext_ln42_15_fu_7252_p1 + zext_ln70_fu_7693_p1);

assign add_ln58_173_fu_9507_p2 = (zext_ln42_28_fu_8155_p1 + zext_ln70_3_fu_8346_p1);

assign add_ln58_174_fu_9513_p2 = (add_ln58_173_fu_9507_p2 + zext_ln73_89_fu_7848_p1);

assign add_ln58_175_fu_9523_p2 = (zext_ln58_45_fu_9519_p1 + zext_ln58_44_fu_9503_p1);

assign add_ln58_176_fu_9533_p2 = ($signed(sext_ln73_17_fu_6996_p1) + $signed(sext_ln73_21_fu_7162_p1));

assign add_ln58_177_fu_9543_p2 = ($signed(sext_ln58_109_fu_9539_p1) + $signed(zext_ln73_114_fu_8507_p1));

assign add_ln58_178_fu_9549_p2 = ($signed(sext_ln73_56_fu_8769_p1) + $signed(9'd448));

assign add_ln58_179_fu_9559_p2 = ($signed(sext_ln58_110_fu_9555_p1) + $signed(sext_ln73_28_fu_7515_p1));

assign add_ln58_180_fu_9569_p2 = ($signed(sext_ln58_111_fu_9565_p1) + $signed(add_ln58_177_fu_9543_p2));

assign add_ln58_181_fu_9579_p2 = ($signed(sext_ln58_112_fu_9575_p1) + $signed(zext_ln58_46_fu_9529_p1));

assign add_ln58_182_fu_9589_p2 = (zext_ln42_14_fu_7215_p1 + zext_ln42_17_fu_7545_p1);

assign add_ln58_183_fu_9599_p2 = ($signed(zext_ln70_2_fu_7933_p1) + $signed(sext_ln70_fu_7037_p1));

assign add_ln58_184_fu_9605_p2 = (add_ln58_183_fu_9599_p2 + zext_ln73_75_fu_7567_p1);

assign add_ln58_185_fu_9615_p2 = ($signed(sext_ln58_114_fu_9611_p1) + $signed(zext_ln58_47_fu_9595_p1));

assign add_ln58_186_fu_9625_p2 = ($signed(sext_ln73_38_fu_8131_p1) + $signed(sext_ln73_41_fu_8249_p1));

assign add_ln58_187_fu_9631_p2 = ($signed(add_ln58_186_fu_9625_p2) + $signed(sext_ln70_10_fu_7400_p1));

assign add_ln58_188_fu_9641_p2 = ($signed(sext_ln58_fu_8773_p1) + $signed(10'd320));

assign add_ln58_189_fu_9651_p2 = ($signed(zext_ln58_48_fu_9647_p1) + $signed(sext_ln70_11_fu_8596_p1));

assign add_ln58_190_fu_9661_p2 = ($signed(sext_ln58_117_fu_9657_p1) + $signed(sext_ln58_116_fu_9637_p1));

assign add_ln58_191_fu_9671_p2 = ($signed(sext_ln58_118_fu_9667_p1) + $signed(sext_ln58_115_fu_9621_p1));

assign add_ln58_96_fu_8797_p2 = (zext_ln42_16_fu_7511_p1 + zext_ln42_24_fu_8576_p1);

assign add_ln58_97_fu_8803_p2 = (add_ln58_96_fu_8797_p2 + zext_ln73_80_fu_7680_p1);

assign add_ln58_98_fu_8813_p2 = (zext_ln58_24_fu_8809_p1 + zext_ln58_23_fu_8793_p1);

assign add_ln58_99_fu_8823_p2 = ($signed(sext_ln73_20_fu_7111_p1) + $signed(sext_ln73_35_fu_7913_p1));

assign add_ln58_fu_8787_p2 = (zext_ln42_12_fu_6976_p1 + zext_ln42_27_fu_7369_p1);

assign add_ln73_2_fu_7298_p2 = (zext_ln73_60_fu_7283_p1 + zext_ln73_61_fu_7294_p1);

assign add_ln73_3_fu_7329_p2 = (zext_ln73_63_fu_7325_p1 + zext_ln73_58_fu_7222_p1);

assign add_ln73_4_fu_7637_p2 = (zext_ln73_76_fu_7578_p1 + zext_ln73_78_fu_7633_p1);

assign add_ln73_5_fu_7828_p2 = (zext_ln73_88_fu_7824_p1 + zext_ln73_84_fu_7725_p1);

assign add_ln73_6_fu_8005_p2 = (zext_ln73_95_fu_7990_p1 + zext_ln73_96_fu_8001_p1);

assign add_ln73_fu_6825_p2 = (zext_ln73_44_reg_9850 + zext_ln73_43_fu_6807_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign lshr_ln42_17_fu_6966_p4 = {{sub_ln73_29_fu_6960_p2[11:1]}};

assign lshr_ln42_18_fu_7056_p4 = {{mul_ln73_4_fu_212_p2[9:1]}};

assign lshr_ln42_19_fu_7121_p4 = {{sub_ln73_33_fu_7115_p2[11:1]}};

assign lshr_ln42_20_fu_7170_p4 = {{mul_ln73_6_fu_292_p2[10:1]}};

assign lshr_ln42_21_fu_7242_p4 = {{sub_ln73_36_fu_7236_p2[11:1]}};

assign lshr_ln42_22_fu_7335_p4 = {{add_ln73_3_fu_7329_p2[8:1]}};

assign lshr_ln42_23_fu_7501_p4 = {{mul_ln73_8_fu_266_p2[10:1]}};

assign lshr_ln42_24_fu_7535_p4 = {{sub_ln73_42_fu_7529_p2[11:1]}};

assign lshr_ln42_25_fu_7643_p4 = {{add_ln73_4_fu_7637_p2[10:1]}};

assign lshr_ln42_26_fu_7666_p4 = {{sub_ln73_45_fu_7660_p2[11:1]}};

assign lshr_ln42_28_fu_7683_p4 = {{mul_ln73_9_fu_291_p2[10:1]}};

assign lshr_ln42_30_fu_7834_p4 = {{add_ln73_5_fu_7828_p2[10:1]}};

assign lshr_ln42_31_fu_7872_p4 = {{mul_ln73_10_fu_282_p2[10:1]}};

assign lshr_ln42_32_fu_7923_p4 = {{sub_ln73_50_fu_7917_p2[11:1]}};

assign lshr_ln42_33_fu_8011_p4 = {{add_ln73_6_fu_8005_p2[10:1]}};

assign lshr_ln42_34_fu_8031_p4 = {{sub_ln73_52_fu_8025_p2[11:1]}};

assign lshr_ln42_35_fu_8045_p4 = {{mul_ln73_11_fu_225_p2[10:1]}};

assign lshr_ln42_36_fu_8059_p4 = {{mul_ln73_12_fu_287_p2[9:1]}};

assign lshr_ln42_37_fu_8219_p4 = {{sub_ln73_56_fu_8213_p2[11:1]}};

assign lshr_ln42_38_fu_8277_p4 = {{mul_ln73_13_fu_289_p2[10:1]}};

assign lshr_ln42_39_fu_8336_p4 = {{mul_ln73_15_fu_276_p2[10:1]}};

assign lshr_ln42_40_fu_8362_p4 = {{mul_ln73_16_fu_260_p2[9:1]}};

assign lshr_ln42_41_fu_8493_p4 = {{sub_ln73_62_fu_8487_p2[11:1]}};

assign lshr_ln42_42_fu_8566_p4 = {{mul_ln73_18_fu_269_p2[10:1]}};

assign lshr_ln42_43_fu_8626_p4 = {{sub_ln73_66_fu_8620_p2[11:1]}};

assign lshr_ln42_44_fu_8735_p4 = {{sub_ln73_71_fu_8729_p2[11:1]}};

assign lshr_ln42_s_fu_6888_p4 = {{sub_ln73_25_fu_6882_p2[11:1]}};

assign lshr_ln_fu_6811_p4 = {{mul_ln73_fu_221_p2[10:1]}};

assign mul_ln73_10_fu_282_p0 = zext_ln73_81_fu_7700_p1;

assign mul_ln73_10_fu_282_p1 = 11'd22;

assign mul_ln73_11_fu_225_p0 = zext_ln73_93_fu_7944_p1;

assign mul_ln73_11_fu_225_p1 = 11'd25;

assign mul_ln73_12_fu_287_p0 = zext_ln73_92_fu_7940_p1;

assign mul_ln73_12_fu_287_p1 = 10'd13;

assign mul_ln73_13_fu_289_p0 = zext_ln73_103_fu_8166_p1;

assign mul_ln73_13_fu_289_p1 = 11'd26;

assign mul_ln73_14_fu_204_p0 = zext_ln73_16_fu_8159_p1;

assign mul_ln73_14_fu_204_p1 = 12'd4077;

assign mul_ln73_15_fu_276_p0 = zext_ln73_103_fu_8166_p1;

assign mul_ln73_15_fu_276_p1 = 11'd19;

assign mul_ln73_16_fu_260_p0 = zext_ln73_108_fu_8358_p1;

assign mul_ln73_16_fu_260_p1 = 10'd11;

assign mul_ln73_17_fu_298_p0 = zext_ln73_17_fu_8350_p1;

assign mul_ln73_17_fu_298_p1 = 12'd4071;

assign mul_ln73_18_fu_269_p0 = zext_ln73_107_fu_8354_p1;

assign mul_ln73_18_fu_269_p1 = 11'd27;

assign mul_ln73_4_fu_212_p0 = mul_ln73_4_fu_212_p00;

assign mul_ln73_4_fu_212_p00 = data_1_val_read_reg_9828;

assign mul_ln73_4_fu_212_p1 = 10'd11;

assign mul_ln73_5_fu_234_p0 = zext_ln73_10_fu_7041_p1;

assign mul_ln73_5_fu_234_p1 = 12'd4075;

assign mul_ln73_6_fu_292_p0 = mul_ln73_6_fu_292_p00;

assign mul_ln73_6_fu_292_p00 = data_1_val_read_reg_9828;

assign mul_ln73_6_fu_292_p1 = 11'd21;

assign mul_ln73_7_fu_211_p0 = zext_ln73_66_fu_7404_p1;

assign mul_ln73_7_fu_211_p1 = 11'd2037;

assign mul_ln73_8_fu_266_p0 = zext_ln73_66_fu_7404_p1;

assign mul_ln73_8_fu_266_p1 = 11'd26;

assign mul_ln73_9_fu_291_p0 = mul_ln73_9_fu_291_p00;

assign mul_ln73_9_fu_291_p00 = data_4_val_read_reg_9796;

assign mul_ln73_9_fu_291_p1 = 11'd19;

assign mul_ln73_fu_221_p0 = zext_ln73_43_fu_6807_p1;

assign mul_ln73_fu_221_p1 = 11'd22;

assign sext_ln42_1_fu_7365_p1 = $signed(trunc_ln42_21_fu_7355_p4);

assign sext_ln42_2_fu_7780_p1 = $signed(trunc_ln42_30_fu_7770_p4);

assign sext_ln42_3_fu_8151_p1 = $signed(trunc_ln42_37_fu_8141_p4);

assign sext_ln42_4_fu_8418_p1 = $signed(trunc_ln42_44_fu_8408_p4);

assign sext_ln42_fu_7211_p1 = $signed(trunc_ln42_19_fu_7201_p4);

assign sext_ln58_100_fu_9359_p1 = $signed(add_ln58_156_fu_9353_p2);

assign sext_ln58_101_fu_9369_p1 = $signed(add_ln58_157_fu_9363_p2);

assign sext_ln58_102_fu_9379_p1 = $signed(add_ln58_158_fu_9373_p2);

assign sext_ln58_103_fu_9395_p1 = $signed(add_ln58_160_fu_9389_p2);

assign sext_ln58_104_fu_9405_p1 = $signed(add_ln58_161_fu_9399_p2);

assign sext_ln58_105_fu_9457_p1 = $signed(add_ln58_167_fu_9451_p2);

assign sext_ln58_106_fu_9473_p1 = $signed(add_ln58_169_fu_9467_p2);

assign sext_ln58_107_fu_9483_p1 = $signed(add_ln58_170_fu_9477_p2);

assign sext_ln58_108_fu_9493_p1 = $signed(add_ln58_171_fu_9487_p2);

assign sext_ln58_109_fu_9539_p1 = $signed(add_ln58_176_fu_9533_p2);

assign sext_ln58_110_fu_9555_p1 = $signed(add_ln58_178_fu_9549_p2);

assign sext_ln58_111_fu_9565_p1 = $signed(add_ln58_179_fu_9559_p2);

assign sext_ln58_112_fu_9575_p1 = $signed(add_ln58_180_fu_9569_p2);

assign sext_ln58_113_fu_9585_p1 = $signed(add_ln58_181_fu_9579_p2);

assign sext_ln58_114_fu_9611_p1 = $signed(add_ln58_184_fu_9605_p2);

assign sext_ln58_115_fu_9621_p1 = $signed(add_ln58_185_fu_9615_p2);

assign sext_ln58_116_fu_9637_p1 = $signed(add_ln58_187_fu_9631_p2);

assign sext_ln58_117_fu_9657_p1 = $signed(add_ln58_189_fu_9651_p2);

assign sext_ln58_118_fu_9667_p1 = $signed(add_ln58_190_fu_9661_p2);

assign sext_ln58_68_fu_8829_p1 = $signed(add_ln58_99_fu_8823_p2);

assign sext_ln58_69_fu_8839_p1 = $signed(add_ln58_100_fu_8833_p2);

assign sext_ln58_70_fu_8855_p1 = $signed(add_ln58_102_fu_8849_p2);

assign sext_ln58_71_fu_8865_p1 = $signed(add_ln58_103_fu_8859_p2);

assign sext_ln58_72_fu_8923_p1 = $signed(add_ln58_110_fu_8917_p2);

assign sext_ln58_73_fu_8933_p1 = $signed(add_ln58_111_fu_8927_p2);

assign sext_ln58_74_fu_8943_p1 = $signed(add_ln58_112_fu_8937_p2);

assign sext_ln58_75_fu_8953_p1 = $signed(add_ln58_113_fu_8947_p2);

assign sext_ln58_76_fu_8999_p1 = $signed(add_ln58_118_fu_8993_p2);

assign sext_ln58_77_fu_9009_p1 = $signed(add_ln58_119_fu_9003_p2);

assign sext_ln58_78_fu_9025_p1 = $signed(add_ln58_121_fu_9019_p2);

assign sext_ln58_79_fu_9035_p1 = $signed(add_ln58_122_fu_9029_p2);

assign sext_ln58_80_fu_9045_p1 = $signed(add_ln58_123_fu_9039_p2);

assign sext_ln58_81_fu_9091_p1 = $signed(add_ln58_128_fu_9085_p2);

assign sext_ln58_82_fu_9101_p1 = $signed(add_ln58_129_fu_9095_p2);

assign sext_ln58_83_fu_9111_p1 = $signed(add_ln58_130_fu_9105_p2);

assign sext_ln58_84_fu_9121_p1 = $signed(add_ln58_131_fu_9115_p2);

assign sext_ln58_85_fu_9131_p1 = $signed(add_ln58_132_fu_9125_p2);

assign sext_ln58_86_fu_9157_p1 = $signed(add_ln58_135_fu_9151_p2);

assign sext_ln58_87_fu_9167_p1 = $signed(add_ln58_136_fu_9161_p2);

assign sext_ln58_88_fu_9177_p1 = $signed(add_ln58_137_fu_9171_p2);

assign sext_ln58_89_fu_9193_p1 = $signed(add_ln58_139_fu_9187_p2);

assign sext_ln58_90_fu_9203_p1 = $signed(add_ln58_140_fu_9197_p2);

assign sext_ln58_91_fu_9213_p1 = $signed(add_ln58_141_fu_9207_p2);

assign sext_ln58_92_fu_9223_p1 = $signed(add_ln58_142_fu_9217_p2);

assign sext_ln58_93_fu_9279_p1 = $signed(add_ln58_148_fu_9273_p2);

assign sext_ln58_94_fu_9289_p1 = $signed(add_ln58_149_fu_9283_p2);

assign sext_ln58_95_fu_9299_p1 = $signed(add_ln58_150_fu_9293_p2);

assign sext_ln58_96_fu_9309_p1 = $signed(add_ln58_151_fu_9303_p2);

assign sext_ln58_97_fu_9329_p1 = $signed(add_ln58_153_fu_9323_p2);

assign sext_ln58_98_fu_9339_p1 = $signed(add_ln58_154_fu_9333_p2);

assign sext_ln58_99_fu_9349_p1 = $signed(add_ln58_155_fu_9343_p2);

assign sext_ln58_fu_8773_p1 = $signed(trunc_ln42_53_reg_9890);

assign sext_ln68_fu_9677_p1 = $signed(add_ln58_191_fu_9671_p2);

assign sext_ln70_10_fu_7400_p1 = $signed(trunc_ln42_22_fu_7390_p4);

assign sext_ln70_11_fu_8596_p1 = $signed(trunc_ln42_48_fu_8586_p4);

assign sext_ln70_fu_7037_p1 = $signed(trunc_ln42_15_fu_7027_p4);

assign sext_ln73_14_fu_6902_p1 = $signed(sub_ln73_26_reg_9860);

assign sext_ln73_15_fu_6921_p1 = $signed(trunc_ln4_fu_6911_p4);

assign sext_ln73_16_fu_6956_p1 = $signed(trunc_ln42_s_fu_6946_p4);

assign sext_ln73_17_fu_6996_p1 = $signed(trunc_ln42_14_fu_6986_p4);

assign sext_ln73_18_fu_7017_p1 = $signed(sub_ln73_30_fu_7011_p2);

assign sext_ln73_19_fu_7080_p1 = $signed(trunc_ln42_16_fu_7070_p4);

assign sext_ln73_20_fu_7111_p1 = $signed(trunc_ln42_17_fu_7101_p4);

assign sext_ln73_21_fu_7162_p1 = trunc_ln42_18_fu_7152_p4;

assign sext_ln73_22_fu_7166_p1 = trunc_ln42_18_fu_7152_p4;

assign sext_ln73_23_fu_7272_p1 = $signed(trunc_ln42_20_fu_7262_p4);

assign sext_ln73_24_fu_7460_p1 = $signed(trunc_ln42_23_fu_7450_p4);

assign sext_ln73_25_fu_7464_p1 = sub_ln73_40_reg_9865;

assign sext_ln73_26_fu_7483_p1 = $signed(trunc_ln42_24_fu_7473_p4);

assign sext_ln73_27_fu_7497_p1 = $signed(trunc_ln42_25_fu_7487_p4);

assign sext_ln73_28_fu_7515_p1 = $signed(trunc_ln42_26_reg_9870);

assign sext_ln73_29_fu_7598_p1 = $signed(trunc_ln42_27_fu_7588_p4);

assign sext_ln73_30_fu_7629_p1 = $signed(trunc_ln42_28_fu_7619_p4);

assign sext_ln73_31_fu_7749_p1 = $signed(trunc_ln42_29_fu_7739_p4);

assign sext_ln73_32_fu_7793_p1 = $signed(sub_ln73_48_fu_7787_p2);

assign sext_ln73_33_fu_7813_p1 = $signed(trunc_ln42_31_fu_7803_p4);

assign sext_ln73_34_fu_7868_p1 = $signed(trunc_ln42_32_fu_7858_p4);

assign sext_ln73_35_fu_7913_p1 = $signed(trunc_ln42_33_fu_7903_p4);

assign sext_ln73_36_fu_7975_p1 = trunc_ln42_34_fu_7965_p4;

assign sext_ln73_37_fu_7979_p1 = trunc_ln42_34_fu_7965_p4;

assign sext_ln73_38_fu_8131_p1 = $signed(trunc_ln42_36_fu_8121_p4);

assign sext_ln73_39_fu_8100_p1 = $signed(trunc_ln42_35_fu_8090_p4);

assign sext_ln73_40_fu_8198_p1 = $signed(trunc_ln42_40_fu_8188_p4);

assign sext_ln73_41_fu_8249_p1 = trunc_ln42_38_fu_8239_p4;

assign sext_ln73_42_fu_8253_p1 = trunc_ln42_38_fu_8239_p4;

assign sext_ln73_43_fu_8273_p1 = $signed(trunc_ln42_39_fu_8263_p4);

assign sext_ln73_44_fu_8318_p1 = $signed(trunc_ln42_43_fu_8308_p4);

assign sext_ln73_45_fu_8332_p1 = $signed(trunc_ln42_41_fu_8322_p4);

assign sext_ln73_46_fu_8453_p1 = $signed(trunc_ln42_42_fu_8443_p4);

assign sext_ln73_47_fu_8463_p1 = $signed(sub_ln73_60_fu_8457_p2);

assign sext_ln73_48_fu_8483_p1 = $signed(trunc_ln42_46_fu_8473_p4);

assign sext_ln73_49_fu_8528_p1 = $signed(sub_ln73_63_fu_8522_p2);

assign sext_ln73_50_fu_8548_p1 = $signed(trunc_ln42_47_fu_8538_p4);

assign sext_ln73_51_fu_8562_p1 = $signed(trunc_ln42_45_fu_8552_p4);

assign sext_ln73_52_fu_8644_p1 = $signed(sub_ln73_67_reg_9885);

assign sext_ln73_53_fu_8663_p1 = $signed(trunc_ln42_50_fu_8653_p4);

assign sext_ln73_54_fu_8694_p1 = $signed(trunc_ln42_51_fu_8684_p4);

assign sext_ln73_55_fu_8714_p1 = $signed(trunc_ln42_49_fu_8704_p4);

assign sext_ln73_56_fu_8769_p1 = $signed(trunc_ln42_52_fu_8759_p4);

assign sext_ln73_fu_6867_p1 = $signed(trunc_ln42_13_fu_6857_p4);

assign shl_ln73_15_fu_6840_p3 = {{data_0_val_read_reg_9839}, {5'd0}};

assign shl_ln73_16_fu_6871_p3 = {{data_0_val_read_reg_9839}, {2'd0}};

assign shl_ln73_17_fu_6925_p3 = {{data_0_val_read_reg_9839}, {1'd0}};

assign shl_ln73_18_fu_7000_p3 = {{data_0_val_read_reg_9839}, {3'd0}};

assign shl_ln73_19_fu_7084_p3 = {{data_1_val_read_reg_9828}, {5'd0}};

assign shl_ln73_1_fu_7429_p3 = {{data_3_val_read_reg_9806}, {2'd0}};

assign shl_ln73_20_fu_7135_p3 = {{data_1_val_read_reg_9828}, {1'd0}};

assign shl_ln73_21_fu_7184_p3 = {{data_1_val_read_reg_9828}, {2'd0}};

assign shl_ln73_22_fu_7225_p3 = {{data_2_val_read_reg_9817}, {5'd0}};

assign shl_ln73_23_fu_7276_p3 = {{data_2_val_read_reg_9817}, {3'd0}};

assign shl_ln73_24_fu_7287_p3 = {{data_2_val_read_reg_9817}, {1'd0}};

assign shl_ln73_25_fu_7314_p3 = {{data_2_val_read_reg_9817}, {2'd0}};

assign shl_ln73_26_fu_7373_p3 = {{data_2_val_read_reg_9817}, {4'd0}};

assign shl_ln73_27_fu_6715_p3 = {{data_3_val}, {4'd0}};

assign shl_ln73_28_fu_7518_p3 = {{data_3_val_read_reg_9806}, {5'd0}};

assign shl_ln73_29_fu_7571_p3 = {{data_4_val_read_reg_9796}, {4'd0}};

assign shl_ln73_30_fu_7602_p3 = {{data_4_val_read_reg_9796}, {5'd0}};

assign shl_ln73_31_fu_7707_p3 = {{data_5_val_read_reg_9784}, {3'd0}};

assign shl_ln73_32_fu_7718_p3 = {{data_5_val_read_reg_9784}, {1'd0}};

assign shl_ln73_33_fu_7753_p3 = {{data_5_val_read_reg_9784}, {5'd0}};

assign shl_ln73_34_fu_7817_p3 = {{data_5_val_read_reg_9784}, {4'd0}};

assign shl_ln73_35_fu_7948_p3 = {{data_6_val_read_reg_9772}, {5'd0}};

assign shl_ln73_36_fu_7983_p3 = {{data_6_val_read_reg_9772}, {4'd0}};

assign shl_ln73_37_fu_7994_p3 = {{data_6_val_read_reg_9772}, {2'd0}};

assign shl_ln73_38_fu_8073_p3 = {{data_6_val_read_reg_9772}, {1'd0}};

assign shl_ln73_39_fu_8171_p3 = {{data_7_val_read_reg_9762}, {1'd0}};

assign shl_ln73_40_fu_8202_p3 = {{data_7_val_read_reg_9762}, {5'd0}};

assign shl_ln73_41_fu_8376_p3 = {{data_8_val_read_reg_9751}, {3'd0}};

assign shl_ln73_42_fu_8387_p3 = {{data_8_val_read_reg_9751}, {1'd0}};

assign shl_ln73_43_fu_8426_p3 = {{data_8_val_read_reg_9751}, {5'd0}};

assign shl_ln73_44_fu_8511_p3 = {{data_8_val_read_reg_9751}, {2'd0}};

assign shl_ln73_45_fu_8609_p3 = {{data_9_val_read_reg_9741}, {5'd0}};

assign shl_ln73_46_fu_6767_p3 = {{data_9_val}, {3'd0}};

assign shl_ln73_47_fu_8667_p3 = {{data_9_val_read_reg_9741}, {1'd0}};

assign shl_ln73_48_fu_8718_p3 = {{data_9_val_read_reg_9741}, {2'd0}};

assign shl_ln73_s_fu_6687_p3 = {{data_0_val}, {4'd0}};

assign shl_ln_fu_7415_p3 = {{data_3_val_read_reg_9806}, {1'd0}};

assign sub_ln73_1_fu_7444_p2 = (7'd0 - zext_ln73_68_fu_7412_p1);

assign sub_ln73_24_fu_6851_p2 = (12'd0 - zext_ln73_45_fu_6847_p1);

assign sub_ln73_25_fu_6882_p2 = (zext_ln73_45_fu_6847_p1 - zext_ln73_46_fu_6878_p1);

assign sub_ln73_26_fu_6709_p2 = (11'd0 - zext_ln73_44_fu_6695_p1);

assign sub_ln73_27_fu_6905_p2 = ($signed(sext_ln73_14_fu_6902_p1) - $signed(zext_ln73_fu_6801_p1));

assign sub_ln73_28_fu_6940_p2 = (8'd0 - zext_ln73_48_fu_6936_p1);

assign sub_ln73_29_fu_6960_p2 = (zext_ln73_45_fu_6847_p1 - zext_ln73_fu_6801_p1);

assign sub_ln73_30_fu_7011_p2 = (10'd0 - zext_ln73_49_fu_7007_p1);

assign sub_ln73_31_fu_7021_p2 = ($signed(sext_ln73_18_fu_7017_p1) - $signed(zext_ln73_47_fu_6932_p1));

assign sub_ln73_32_fu_7095_p2 = (12'd0 - zext_ln73_54_fu_7091_p1);

assign sub_ln73_33_fu_7115_p2 = (zext_ln73_54_fu_7091_p1 - zext_ln73_10_fu_7041_p1);

assign sub_ln73_34_fu_7146_p2 = (zext_ln73_55_fu_7142_p1 - zext_ln73_54_fu_7091_p1);

assign sub_ln73_35_fu_7195_p2 = (zext_ln73_57_fu_7191_p1 - zext_ln73_50_fu_7045_p1);

assign sub_ln73_36_fu_7236_p2 = (zext_ln73_59_fu_7232_p1 - zext_ln73_11_fu_7219_p1);

assign sub_ln73_37_fu_7256_p2 = (12'd0 - zext_ln73_59_fu_7232_p1);

assign sub_ln73_38_fu_7349_p2 = (zext_ln73_60_fu_7283_p1 - zext_ln73_61_fu_7294_p1);

assign sub_ln73_39_fu_7384_p2 = (zext_ln73_62_fu_7321_p1 - zext_ln73_65_fu_7380_p1);

assign sub_ln73_40_fu_6727_p2 = (11'd0 - zext_ln73_71_fu_6723_p1);

assign sub_ln73_41_fu_7467_p2 = ($signed(sext_ln73_25_fu_7464_p1) - $signed(zext_ln42_2_fu_7422_p1));

assign sub_ln73_42_fu_7529_p2 = (zext_ln73_72_fu_7525_p1 - zext_ln42_3_fu_7436_p1);

assign sub_ln73_43_fu_7582_p2 = (11'd0 - zext_ln73_76_fu_7578_p1);

assign sub_ln73_44_fu_7613_p2 = (12'd0 - zext_ln73_77_fu_7609_p1);

assign sub_ln73_45_fu_7660_p2 = (zext_ln73_77_fu_7609_p1 - zext_ln73_13_fu_7549_p1);

assign sub_ln73_46_fu_7733_p2 = (zext_ln73_85_fu_7729_p1 - zext_ln73_83_fu_7714_p1);

assign sub_ln73_47_fu_7764_p2 = (12'd0 - zext_ln73_86_fu_7760_p1);

assign sub_ln73_48_fu_7787_p2 = (10'd0 - zext_ln73_83_fu_7714_p1);

assign sub_ln73_49_fu_7797_p2 = ($signed(sext_ln73_32_fu_7793_p1) - $signed(zext_ln73_81_fu_7700_p1));

assign sub_ln73_50_fu_7917_p2 = (zext_ln73_86_fu_7760_p1 - zext_ln73_14_fu_7697_p1);

assign sub_ln73_51_fu_7959_p2 = (12'd0 - zext_ln73_94_fu_7955_p1);

assign sub_ln73_52_fu_8025_p2 = (zext_ln73_94_fu_7955_p1 - zext_ln73_15_fu_7937_p1);

assign sub_ln73_53_fu_8084_p2 = (zext_ln73_100_fu_8080_p1 - zext_ln73_95_fu_7990_p1);

assign sub_ln73_54_fu_8135_p2 = (zext_ln73_95_fu_7990_p1 - zext_ln73_93_fu_7944_p1);

assign sub_ln73_55_fu_8182_p2 = (8'd0 - zext_ln73_104_fu_8178_p1);

assign sub_ln73_56_fu_8213_p2 = (zext_ln73_105_fu_8209_p1 - zext_ln73_16_fu_8159_p1);

assign sub_ln73_57_fu_8233_p2 = (12'd0 - zext_ln73_105_fu_8209_p1);

assign sub_ln73_58_fu_8402_p2 = (zext_ln73_110_fu_8383_p1 - zext_ln73_112_fu_8398_p1);

assign sub_ln73_59_fu_8437_p2 = (12'd0 - zext_ln73_113_fu_8433_p1);

assign sub_ln73_60_fu_8457_p2 = (10'd0 - zext_ln73_110_fu_8383_p1);

assign sub_ln73_61_fu_8467_p2 = ($signed(sext_ln73_47_fu_8463_p1) - $signed(zext_ln73_107_fu_8354_p1));

assign sub_ln73_62_fu_8487_p2 = (zext_ln73_113_fu_8433_p1 - zext_ln73_17_fu_8350_p1);

assign sub_ln73_63_fu_8522_p2 = (9'd0 - zext_ln73_115_fu_8518_p1);

assign sub_ln73_64_fu_8532_p2 = ($signed(sext_ln73_49_fu_8528_p1) - $signed(zext_ln73_108_fu_8358_p1));

assign sub_ln73_65_fu_8580_p2 = ($signed(sext_ln73_47_fu_8463_p1) - $signed(zext_ln73_111_fu_8394_p1));

assign sub_ln73_66_fu_8620_p2 = (zext_ln73_119_fu_8616_p1 - zext_ln73_18_fu_8600_p1);

assign sub_ln73_67_fu_6779_p2 = (10'd0 - zext_ln73_121_fu_6775_p1);

assign sub_ln73_68_fu_8647_p2 = ($signed(sext_ln73_52_fu_8644_p1) - $signed(zext_ln73_118_fu_8606_p1));

assign sub_ln73_69_fu_8678_p2 = (8'd0 - zext_ln73_122_fu_8674_p1);

assign sub_ln73_70_fu_8698_p2 = (12'd0 - zext_ln73_119_fu_8616_p1);

assign sub_ln73_71_fu_8729_p2 = (zext_ln73_119_fu_8616_p1 - zext_ln73_123_fu_8725_p1);

assign sub_ln73_72_fu_7852_p2 = (zext_ln73_14_fu_7697_p1 - zext_ln73_86_fu_7760_p1);

assign sub_ln73_73_fu_7897_p2 = (zext_ln73_82_fu_7704_p1 - zext_ln73_91_fu_7893_p1);

assign sub_ln73_74_fu_8115_p2 = (zext_ln73_92_fu_7940_p1 - zext_ln73_101_fu_8111_p1);

assign sub_ln73_75_fu_8257_p2 = (zext_ln73_16_fu_8159_p1 - zext_ln73_105_fu_8209_p1);

assign sub_ln73_76_fu_8302_p2 = (zext_ln73_102_fu_8163_p1 - zext_ln73_106_fu_8298_p1);

assign sub_ln73_77_fu_8753_p2 = (zext_ln73_117_fu_8603_p1 - zext_ln73_124_fu_8749_p1);

assign sub_ln73_78_fu_6785_p2 = (zext_ln73_116_fu_6763_p1 - zext_ln73_121_fu_6775_p1);

assign sub_ln73_fu_6980_p2 = (7'd0 - zext_ln73_42_fu_6804_p1);

assign tmp_1_fu_7556_p3 = {{data_4_val_read_reg_9796}, {1'd0}};

assign tmp_3_fu_7886_p3 = {{data_5_val_read_reg_9784}, {2'd0}};

assign tmp_4_fu_8104_p3 = {{data_6_val_read_reg_9772}, {3'd0}};

assign tmp_6_fu_8291_p3 = {{data_7_val_read_reg_9762}, {2'd0}};

assign trunc_ln42_13_fu_6857_p4 = {{sub_ln73_24_fu_6851_p2[11:1]}};

assign trunc_ln42_14_fu_6986_p4 = {{sub_ln73_fu_6980_p2[6:1]}};

assign trunc_ln42_15_fu_7027_p4 = {{sub_ln73_31_fu_7021_p2[10:1]}};

assign trunc_ln42_16_fu_7070_p4 = {{mul_ln73_5_fu_234_p2[11:1]}};

assign trunc_ln42_17_fu_7101_p4 = {{sub_ln73_32_fu_7095_p2[11:1]}};

assign trunc_ln42_18_fu_7152_p4 = {{sub_ln73_34_fu_7146_p2[11:1]}};

assign trunc_ln42_19_fu_7201_p4 = {{sub_ln73_35_fu_7195_p2[8:1]}};

assign trunc_ln42_20_fu_7262_p4 = {{sub_ln73_37_fu_7256_p2[11:1]}};

assign trunc_ln42_21_fu_7355_p4 = {{sub_ln73_38_fu_7349_p2[9:1]}};

assign trunc_ln42_22_fu_7390_p4 = {{sub_ln73_39_fu_7384_p2[10:1]}};

assign trunc_ln42_23_fu_7450_p4 = {{sub_ln73_1_fu_7444_p2[6:1]}};

assign trunc_ln42_24_fu_7473_p4 = {{sub_ln73_41_fu_7467_p2[11:1]}};

assign trunc_ln42_25_fu_7487_p4 = {{mul_ln73_7_fu_211_p2[10:1]}};

assign trunc_ln42_27_fu_7588_p4 = {{sub_ln73_43_fu_7582_p2[10:1]}};

assign trunc_ln42_28_fu_7619_p4 = {{sub_ln73_44_fu_7613_p2[11:1]}};

assign trunc_ln42_29_fu_7739_p4 = {{sub_ln73_46_fu_7733_p2[9:1]}};

assign trunc_ln42_30_fu_7770_p4 = {{sub_ln73_47_fu_7764_p2[11:1]}};

assign trunc_ln42_31_fu_7803_p4 = {{sub_ln73_49_fu_7797_p2[10:1]}};

assign trunc_ln42_32_fu_7858_p4 = {{sub_ln73_72_fu_7852_p2[11:1]}};

assign trunc_ln42_33_fu_7903_p4 = {{sub_ln73_73_fu_7897_p2[8:1]}};

assign trunc_ln42_34_fu_7965_p4 = {{sub_ln73_51_fu_7959_p2[11:1]}};

assign trunc_ln42_35_fu_8090_p4 = {{sub_ln73_53_fu_8084_p2[10:1]}};

assign trunc_ln42_36_fu_8121_p4 = {{sub_ln73_74_fu_8115_p2[9:1]}};

assign trunc_ln42_37_fu_8141_p4 = {{sub_ln73_54_fu_8135_p2[10:1]}};

assign trunc_ln42_38_fu_8239_p4 = {{sub_ln73_57_fu_8233_p2[11:1]}};

assign trunc_ln42_39_fu_8263_p4 = {{sub_ln73_75_fu_8257_p2[11:1]}};

assign trunc_ln42_40_fu_8188_p4 = {{sub_ln73_55_fu_8182_p2[7:1]}};

assign trunc_ln42_41_fu_8322_p4 = {{mul_ln73_14_fu_204_p2[11:1]}};

assign trunc_ln42_42_fu_8443_p4 = {{sub_ln73_59_fu_8437_p2[11:1]}};

assign trunc_ln42_43_fu_8308_p4 = {{sub_ln73_76_fu_8302_p2[8:1]}};

assign trunc_ln42_44_fu_8408_p4 = {{sub_ln73_58_fu_8402_p2[9:1]}};

assign trunc_ln42_45_fu_8552_p4 = {{mul_ln73_17_fu_298_p2[11:1]}};

assign trunc_ln42_46_fu_8473_p4 = {{sub_ln73_61_fu_8467_p2[10:1]}};

assign trunc_ln42_47_fu_8538_p4 = {{sub_ln73_64_fu_8532_p2[9:1]}};

assign trunc_ln42_48_fu_8586_p4 = {{sub_ln73_65_fu_8580_p2[10:1]}};

assign trunc_ln42_49_fu_8704_p4 = {{sub_ln73_70_fu_8698_p2[11:1]}};

assign trunc_ln42_50_fu_8653_p4 = {{sub_ln73_68_fu_8647_p2[10:1]}};

assign trunc_ln42_51_fu_8684_p4 = {{sub_ln73_69_fu_8678_p2[7:1]}};

assign trunc_ln42_52_fu_8759_p4 = {{sub_ln73_77_fu_8753_p2[8:1]}};

assign trunc_ln42_s_fu_6946_p4 = {{sub_ln73_28_fu_6940_p2[7:1]}};

assign trunc_ln4_fu_6911_p4 = {{sub_ln73_27_fu_6905_p2[11:1]}};

assign trunc_ln73_1_fu_7304_p4 = {{add_ln73_2_fu_7298_p2[9:1]}};

assign trunc_ln_fu_6830_p4 = {{add_ln73_fu_6825_p2[10:1]}};

assign zext_ln42_11_fu_6898_p1 = lshr_ln42_s_fu_6888_p4;

assign zext_ln42_12_fu_6976_p1 = lshr_ln42_17_fu_6966_p4;

assign zext_ln42_13_fu_7131_p1 = lshr_ln42_19_fu_7121_p4;

assign zext_ln42_14_fu_7215_p1 = $unsigned(sext_ln42_fu_7211_p1);

assign zext_ln42_15_fu_7252_p1 = lshr_ln42_21_fu_7242_p4;

assign zext_ln42_16_fu_7511_p1 = lshr_ln42_23_fu_7501_p4;

assign zext_ln42_17_fu_7545_p1 = lshr_ln42_24_fu_7535_p4;

assign zext_ln42_18_fu_7676_p1 = lshr_ln42_26_fu_7666_p4;

assign zext_ln42_19_fu_7844_p1 = lshr_ln42_30_fu_7834_p4;

assign zext_ln42_20_fu_8041_p1 = lshr_ln42_34_fu_8031_p4;

assign zext_ln42_21_fu_8229_p1 = lshr_ln42_37_fu_8219_p4;

assign zext_ln42_22_fu_8287_p1 = lshr_ln42_38_fu_8277_p4;

assign zext_ln42_23_fu_8503_p1 = lshr_ln42_41_fu_8493_p4;

assign zext_ln42_24_fu_8576_p1 = lshr_ln42_42_fu_8566_p4;

assign zext_ln42_25_fu_8636_p1 = lshr_ln42_43_fu_8626_p4;

assign zext_ln42_26_fu_8745_p1 = lshr_ln42_44_fu_8735_p4;

assign zext_ln42_27_fu_7369_p1 = $unsigned(sext_ln42_1_fu_7365_p1);

assign zext_ln42_28_fu_8155_p1 = $unsigned(sext_ln42_3_fu_8151_p1);

assign zext_ln42_29_fu_8422_p1 = $unsigned(sext_ln42_4_fu_8418_p1);

assign zext_ln42_2_fu_7422_p1 = shl_ln_fu_7415_p3;

assign zext_ln42_3_fu_7436_p1 = shl_ln73_1_fu_7429_p3;

assign zext_ln42_4_fu_7653_p1 = lshr_ln42_25_fu_7643_p4;

assign zext_ln42_fu_6821_p1 = lshr_ln_fu_6811_p4;

assign zext_ln58_23_fu_8793_p1 = add_ln58_fu_8787_p2;

assign zext_ln58_24_fu_8809_p1 = add_ln58_97_fu_8803_p2;

assign zext_ln58_25_fu_8819_p1 = add_ln58_98_fu_8813_p2;

assign zext_ln58_26_fu_8875_p1 = add_ln58_104_fu_8869_p2;

assign zext_ln58_27_fu_8885_p1 = add_ln58_105_fu_8879_p2;

assign zext_ln58_28_fu_8901_p1 = add_ln58_107_fu_8895_p2;

assign zext_ln58_29_fu_8963_p1 = add_ln58_114_fu_8957_p2;

assign zext_ln58_30_fu_8973_p1 = add_ln58_115_fu_8967_p2;

assign zext_ln58_31_fu_8989_p1 = add_ln58_117_fu_8983_p2;

assign zext_ln58_32_fu_9055_p1 = add_ln58_124_fu_9049_p2;

assign zext_ln58_33_fu_9065_p1 = add_ln58_125_fu_9059_p2;

assign zext_ln58_34_fu_9081_p1 = add_ln58_127_fu_9075_p2;

assign zext_ln58_35_fu_9141_p1 = add_ln58_133_fu_9135_p2;

assign zext_ln58_36_fu_9233_p1 = add_ln58_143_fu_9227_p2;

assign zext_ln58_37_fu_9249_p1 = add_ln58_145_fu_9243_p2;

assign zext_ln58_38_fu_9259_p1 = add_ln58_146_fu_9253_p2;

assign zext_ln58_39_fu_9269_p1 = add_ln58_147_fu_9263_p2;

assign zext_ln58_40_fu_9319_p1 = add_ln58_152_fu_9313_p2;

assign zext_ln58_41_fu_9415_p1 = add_ln58_162_fu_9409_p2;

assign zext_ln58_42_fu_9425_p1 = add_ln58_163_fu_9419_p2;

assign zext_ln58_43_fu_9441_p1 = add_ln58_165_fu_9435_p2;

assign zext_ln58_44_fu_9503_p1 = add_ln58_172_fu_9497_p2;

assign zext_ln58_45_fu_9519_p1 = add_ln58_174_fu_9513_p2;

assign zext_ln58_46_fu_9529_p1 = add_ln58_175_fu_9523_p2;

assign zext_ln58_47_fu_9595_p1 = add_ln58_182_fu_9589_p2;

assign zext_ln58_48_fu_9647_p1 = add_ln58_188_fu_9641_p2;

assign zext_ln58_cast_fu_8776_p3 = {{1'd1}, {lshr_ln42_16_reg_9855}};

assign zext_ln58_fu_8783_p1 = zext_ln58_cast_fu_8776_p3;

assign zext_ln70_2_fu_7933_p1 = lshr_ln42_32_fu_7923_p4;

assign zext_ln70_3_fu_8346_p1 = lshr_ln42_39_fu_8336_p4;

assign zext_ln70_fu_7693_p1 = lshr_ln42_28_fu_7683_p4;

assign zext_ln73_100_fu_8080_p1 = shl_ln73_38_fu_8073_p3;

assign zext_ln73_101_fu_8111_p1 = tmp_4_fu_8104_p3;

assign zext_ln73_102_fu_8163_p1 = data_7_val_read_reg_9762;

assign zext_ln73_103_fu_8166_p1 = data_7_val_read_reg_9762;

assign zext_ln73_104_fu_8178_p1 = shl_ln73_39_fu_8171_p3;

assign zext_ln73_105_fu_8209_p1 = shl_ln73_40_fu_8202_p3;

assign zext_ln73_106_fu_8298_p1 = tmp_6_fu_8291_p3;

assign zext_ln73_107_fu_8354_p1 = data_8_val_read_reg_9751;

assign zext_ln73_108_fu_8358_p1 = data_8_val_read_reg_9751;

assign zext_ln73_109_fu_8372_p1 = lshr_ln42_40_fu_8362_p4;

assign zext_ln73_10_fu_7041_p1 = data_1_val_read_reg_9828;

assign zext_ln73_110_fu_8383_p1 = shl_ln73_41_fu_8376_p3;

assign zext_ln73_111_fu_8394_p1 = shl_ln73_42_fu_8387_p3;

assign zext_ln73_112_fu_8398_p1 = shl_ln73_42_fu_8387_p3;

assign zext_ln73_113_fu_8433_p1 = shl_ln73_43_fu_8426_p3;

assign zext_ln73_114_fu_8507_p1 = lshr_ln42_41_fu_8493_p4;

assign zext_ln73_115_fu_8518_p1 = shl_ln73_44_fu_8511_p3;

assign zext_ln73_116_fu_6763_p1 = data_9_val;

assign zext_ln73_117_fu_8603_p1 = data_9_val_read_reg_9741;

assign zext_ln73_118_fu_8606_p1 = data_9_val_read_reg_9741;

assign zext_ln73_119_fu_8616_p1 = shl_ln73_45_fu_8609_p3;

assign zext_ln73_11_fu_7219_p1 = data_2_val_read_reg_9817;

assign zext_ln73_120_fu_8640_p1 = lshr_ln42_43_fu_8626_p4;

assign zext_ln73_121_fu_6775_p1 = shl_ln73_46_fu_6767_p3;

assign zext_ln73_122_fu_8674_p1 = shl_ln73_47_fu_8667_p3;

assign zext_ln73_123_fu_8725_p1 = shl_ln73_48_fu_8718_p3;

assign zext_ln73_124_fu_8749_p1 = shl_ln73_48_fu_8718_p3;

assign zext_ln73_13_fu_7549_p1 = data_4_val_read_reg_9796;

assign zext_ln73_14_fu_7697_p1 = data_5_val_read_reg_9784;

assign zext_ln73_15_fu_7937_p1 = data_6_val_read_reg_9772;

assign zext_ln73_16_fu_8159_p1 = data_7_val_read_reg_9762;

assign zext_ln73_17_fu_8350_p1 = data_8_val_read_reg_9751;

assign zext_ln73_18_fu_8600_p1 = data_9_val_read_reg_9741;

assign zext_ln73_42_fu_6804_p1 = data_0_val_read_reg_9839;

assign zext_ln73_43_fu_6807_p1 = data_0_val_read_reg_9839;

assign zext_ln73_44_fu_6695_p1 = shl_ln73_s_fu_6687_p3;

assign zext_ln73_45_fu_6847_p1 = shl_ln73_15_fu_6840_p3;

assign zext_ln73_46_fu_6878_p1 = shl_ln73_16_fu_6871_p3;

assign zext_ln73_47_fu_6932_p1 = shl_ln73_17_fu_6925_p3;

assign zext_ln73_48_fu_6936_p1 = shl_ln73_17_fu_6925_p3;

assign zext_ln73_49_fu_7007_p1 = shl_ln73_18_fu_7000_p3;

assign zext_ln73_50_fu_7045_p1 = data_1_val_read_reg_9828;

assign zext_ln73_53_fu_7066_p1 = lshr_ln42_18_fu_7056_p4;

assign zext_ln73_54_fu_7091_p1 = shl_ln73_19_fu_7084_p3;

assign zext_ln73_55_fu_7142_p1 = shl_ln73_20_fu_7135_p3;

assign zext_ln73_56_fu_7180_p1 = lshr_ln42_20_fu_7170_p4;

assign zext_ln73_57_fu_7191_p1 = shl_ln73_21_fu_7184_p3;

assign zext_ln73_58_fu_7222_p1 = data_2_val_read_reg_9817;

assign zext_ln73_59_fu_7232_p1 = shl_ln73_22_fu_7225_p3;

assign zext_ln73_60_fu_7283_p1 = shl_ln73_23_fu_7276_p3;

assign zext_ln73_61_fu_7294_p1 = shl_ln73_24_fu_7287_p3;

assign zext_ln73_62_fu_7321_p1 = shl_ln73_25_fu_7314_p3;

assign zext_ln73_63_fu_7325_p1 = shl_ln73_25_fu_7314_p3;

assign zext_ln73_64_fu_7345_p1 = lshr_ln42_22_fu_7335_p4;

assign zext_ln73_65_fu_7380_p1 = shl_ln73_26_fu_7373_p3;

assign zext_ln73_66_fu_7404_p1 = data_3_val_read_reg_9806;

assign zext_ln73_67_fu_7409_p1 = data_3_val_read_reg_9806;

assign zext_ln73_68_fu_7412_p1 = data_3_val_read_reg_9806;

assign zext_ln73_69_fu_7426_p1 = data_3_val_read_reg_9806;

assign zext_ln73_70_fu_7440_p1 = shl_ln_fu_7415_p3;

assign zext_ln73_71_fu_6723_p1 = shl_ln73_27_fu_6715_p3;

assign zext_ln73_72_fu_7525_p1 = shl_ln73_28_fu_7518_p3;

assign zext_ln73_74_fu_7563_p1 = tmp_1_fu_7556_p3;

assign zext_ln73_75_fu_7567_p1 = tmp_1_fu_7556_p3;

assign zext_ln73_76_fu_7578_p1 = shl_ln73_29_fu_7571_p3;

assign zext_ln73_77_fu_7609_p1 = shl_ln73_30_fu_7602_p3;

assign zext_ln73_78_fu_7633_p1 = tmp_1_fu_7556_p3;

assign zext_ln73_79_fu_7657_p1 = data_4_val_read_reg_9796;

assign zext_ln73_80_fu_7680_p1 = lshr_ln42_27_reg_9875;

assign zext_ln73_81_fu_7700_p1 = data_5_val_read_reg_9784;

assign zext_ln73_82_fu_7704_p1 = data_5_val_read_reg_9784;

assign zext_ln73_83_fu_7714_p1 = shl_ln73_31_fu_7707_p3;

assign zext_ln73_84_fu_7725_p1 = shl_ln73_32_fu_7718_p3;

assign zext_ln73_85_fu_7729_p1 = shl_ln73_32_fu_7718_p3;

assign zext_ln73_86_fu_7760_p1 = shl_ln73_33_fu_7753_p3;

assign zext_ln73_87_fu_7784_p1 = lshr_ln42_29_reg_9880;

assign zext_ln73_88_fu_7824_p1 = shl_ln73_34_fu_7817_p3;

assign zext_ln73_89_fu_7848_p1 = lshr_ln42_30_fu_7834_p4;

assign zext_ln73_90_fu_7882_p1 = lshr_ln42_31_fu_7872_p4;

assign zext_ln73_91_fu_7893_p1 = tmp_3_fu_7886_p3;

assign zext_ln73_92_fu_7940_p1 = data_6_val_read_reg_9772;

assign zext_ln73_93_fu_7944_p1 = data_6_val_read_reg_9772;

assign zext_ln73_94_fu_7955_p1 = shl_ln73_35_fu_7948_p3;

assign zext_ln73_95_fu_7990_p1 = shl_ln73_36_fu_7983_p3;

assign zext_ln73_96_fu_8001_p1 = shl_ln73_37_fu_7994_p3;

assign zext_ln73_97_fu_8021_p1 = lshr_ln42_33_fu_8011_p4;

assign zext_ln73_98_fu_8055_p1 = lshr_ln42_35_fu_8045_p4;

assign zext_ln73_99_fu_8069_p1 = lshr_ln42_36_fu_8059_p4;

assign zext_ln73_fu_6801_p1 = data_0_val_read_reg_9839;

always @ (posedge ap_clk) begin
    zext_ln73_44_reg_9850[3:0] <= 4'b0000;
    zext_ln73_44_reg_9850[10] <= 1'b0;
    sub_ln73_26_reg_9860[3:0] <= 4'b0000;
    sub_ln73_40_reg_9865[3:0] <= 4'b0000;
    sub_ln73_67_reg_9885[2:0] <= 3'b000;
end

endmodule //myproject_dense_latency_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config5_s
